import os
import sys
import numpy as np
import pandas as pd
import joblib
from sklearn.metrics import roc_auc_score
from scipy.stats import pearsonr

# Import library modules
from library.config import Config
from library.stacking import StackingTrainer
from library.utils import seed_everything, get_logger


def main():
    # 1. Setup
    seed_everything(Config.SEED)
    logger = get_logger("runfile")

    # Adjust configuration for a fast baseline execution
    # 32x32 images train quickly, but we limit epochs to ensure <2hr runtime
    Config.EPOCHS = 20

    logger.info("Starting End-to-End Pipeline...")

    # 2. Execution: Train Ensemble and Generate Submission
    # StackingTrainer handles:
    # - Data Loading & Caching
    # - 5-Fold Stratified CV for RepVGG (Spatial/Texture) and ResNet
    # - Training Logistic Regression Meta-Learner
    # - Generating Submission for Test Set
    trainer = StackingTrainer()
    trainer.run()

    # 3. Validation & Failure Analysis
    logger.info("Performing Validation and Failure Analysis...")

    # Load necessary artifacts generated by the trainer
    meta_model_path = os.path.join(Config.WORKING_DIR, "meta_model.joblib")
    val_preds_path = os.path.join(Config.WORKING_DIR, "val_predictions.parquet")

    if not os.path.exists(val_preds_path) or not os.path.exists(meta_model_path):
        logger.error(
            "Required artifacts (Val preds or Meta Model) not found. Pipeline may have failed."
        )
        return

    # Load Validation Predictions (Hold-out set, strictly isolated from Meta-Learner training)
    # Cite Debug Lesson 11: Enforce Strict Isolation Between Training and Hold-Out Validation Sets
    val_subset = pd.read_parquet(val_preds_path)

    # Load Validation Metadata for file sizes
    val_df = pd.read_csv(Config.VAL_METADATA)

    # Prepare Features for Meta-Model Inference
    # 1. Base Model Predictions
    model_cols = list(Config.MODEL_CONFIGS.keys())
    X_base = val_subset[model_cols].values
    y_true = val_subset["target"].values

    # 2. File Size Feature (Meta-Feature)
    # We need to map IDs to file sizes. We can read from disk to be robust.
    val_fsizes = []
    for _, row in val_df.iterrows():
        # Path is relative to input dir
        p = os.path.join(Config.INPUT_DIR, row["file_path"])
        val_fsizes.append(os.path.getsize(p))

    val_fsizes = np.array(val_fsizes).reshape(-1, 1)

    # Scale File Sizes
    # We must use the same scaler used during training.
    # It is stored in the trainer instance after run().
    if hasattr(trainer, "fs_scaler"):
        val_fsizes_scaled = trainer.fs_scaler.transform(val_fsizes)
    else:
        # Fallback: Re-fit scaler on all training data if trainer state is somehow lost
        logger.warning("Scaler not found in trainer, refitting...")
        from sklearn.preprocessing import StandardScaler

        # Load all file sizes (Train + Val) to match training distribution
        all_fsizes = []
        t_df = pd.read_csv(Config.TRAIN_METADATA)
        v_df = pd.read_csv(Config.VAL_METADATA)

        for df in [t_df, v_df]:
            for _, row in df.iterrows():
                p = os.path.join(Config.INPUT_DIR, row["file_path"])
                all_fsizes.append(os.path.getsize(p))

        scaler = StandardScaler()
        scaler.fit(np.array(all_fsizes).reshape(-1, 1))
        val_fsizes_scaled = scaler.transform(val_fsizes)

    # Combine Features
    X_val_full = np.hstack([X_base, val_fsizes_scaled])

    # Load Meta-Model and Predict
    meta_model = joblib.load(meta_model_path)
    val_preds = meta_model.predict_proba(X_val_full)[:, 1]

    # 4. Report Final Validation Metric
    final_auc = roc_auc_score(y_true, val_preds)
    print(f"Final Validation Metric: {final_auc:.16f}")

    # 5. Failure Analysis
    # Calculate Error Magnitude
    errors = np.abs(y_true - val_preds)

    # Correlation with File Size (Quality Proxy)
    corr_size, p_size = pearsonr(errors, val_fsizes.flatten())

    print("-" * 30)
    print("Failure Analysis Report:")
    print(f"Correlation (Error vs File Size): {corr_size:.4f} (p={p_size:.4f})")

    # Interpretation
    if corr_size < 0:
        print(
            "Observation: Higher file sizes (better quality) correlate with lower error."
        )
    else:
        print(
            "Observation: Higher file sizes correlate with higher error (or no correlation)."
        )

    # Correlation with Model Disagreement
    # Standard deviation of base model predictions for each sample
    model_disagreement = np.std(X_base, axis=1)
    corr_disagree, p_disagree = pearsonr(errors, model_disagreement)
    print(f"Correlation (Error vs Model Disagreement): {corr_disagree:.4f}")
    print("-" * 30)

    # Submission is already generated by trainer.run()
    # Check if submission exists
    sub_path = os.path.join(Config.SUBMISSION_DIR, "submission.csv")
    if os.path.exists(sub_path):
        logger.info(f"Submission verified at {sub_path}")
    else:
        logger.error("Submission file missing!")


if __name__ == "__main__":
    main()
