import os
import sys
import pandas as pd
import numpy as np
import torch
import shutil

# Import from the provided library files
from library.config import Config
from library.dataset import get_dataloaders
from library.models import KuzushijiDetector, KuzushijiClassifier
from library.engine import fit_detector, fit_classifier, set_seed
from library.inference import generate_submission
from library.utils import calc_modified_f1


def main():
    print("=== Starting Kuzushiji Recognition Pipeline Demo ===")

    # 1. Setup & Config Overrides for Demo
    # We modify the Config class attributes directly to create a fast demo environment
    Config.WORKING_DIR = "./working/demo_run"
    Config.OUTPUT_DIR = os.path.join(Config.WORKING_DIR, "output")
    Config.CACHE_DIR = os.path.join(Config.WORKING_DIR, "cache")
    Config.CLASS_MAP_PATH = os.path.join(Config.WORKING_DIR, "class_map.npy")

    # Point to mini metadata files we will create shortly
    Config.TRAIN_METADATA = os.path.join(Config.WORKING_DIR, "mini_train.csv")
    Config.VAL_METADATA = os.path.join(Config.WORKING_DIR, "mini_val.csv")
    Config.TEST_METADATA = os.path.join(Config.WORKING_DIR, "mini_test.csv")

    # Reduce compute requirements for speed
    Config.DETECTOR_EPOCHS = 1
    Config.CLASSIFIER_EPOCHS = 1
    Config.DETECTOR_BATCH_SIZE = 2
    Config.CLASSIFIER_BATCH_SIZE = 4
    Config.NUM_WORKERS = 0  # Avoid multiprocessing overhead for tiny demo

    # Re-run setup to create the new working directories
    if os.path.exists(Config.WORKING_DIR):
        shutil.rmtree(Config.WORKING_DIR)
    Config.setup()
    set_seed(Config.SEED)

    print(f"Working Directory: {Config.WORKING_DIR}")

    # 2. Create Mini Metadata Files
    print("\n--- Creating Mini Datasets ---")
    # Load original metadata
    orig_train = pd.read_csv("./metadata/train_metadata.csv")
    orig_val = pd.read_csv("./metadata/val_metadata.csv")
    orig_test = pd.read_csv("./metadata/test_metadata.csv")

    # Sample top N rows
    mini_train = orig_train.head(10)
    mini_val = orig_val.head(5)
    mini_test = orig_test.head(5)

    # Save to working dir
    mini_train.to_csv(Config.TRAIN_METADATA, index=False)
    mini_val.to_csv(Config.VAL_METADATA, index=False)
    mini_test.to_csv(Config.TEST_METADATA, index=False)

    print(f"Created mini_train.csv ({len(mini_train)} rows)")
    print(f"Created mini_val.csv ({len(mini_val)} rows)")
    print(f"Created mini_test.csv ({len(mini_test)} rows)")

    # 3. Verify DataLoaders
    print("\n--- Verifying DataLoaders ---")
    loaders = get_dataloaders(load_cached_data=False)

    # Check Detector Loader
    det_batch = next(iter(loaders["detector_train"]))
    img = det_batch["image"]
    hm = det_batch["hm"]
    print(f"Detector Batch Image Shape: {img.shape}")
    print(f"Detector Batch Heatmap Shape: {hm.shape}")

    assert img.shape == (
        Config.DETECTOR_BATCH_SIZE,
        3,
        Config.DETECTOR_INPUT_SIZE[0],
        Config.DETECTOR_INPUT_SIZE[1],
    )
    assert hm.shape == (
        Config.DETECTOR_BATCH_SIZE,
        1,
        Config.DETECTOR_INPUT_SIZE[0] // 4,
        Config.DETECTOR_INPUT_SIZE[1] // 4,
    )

    # Check Classifier Loader
    cls_batch_img, cls_batch_lbl = next(iter(loaders["classifier_train"]))
    print(f"Classifier Batch Image Shape: {cls_batch_img.shape}")
    print(f"Classifier Batch Label Shape: {cls_batch_lbl.shape}")

    assert cls_batch_img.shape == (
        Config.CLASSIFIER_BATCH_SIZE,
        3,
        Config.CLASSIFIER_INPUT_SIZE[0],
        Config.CLASSIFIER_INPUT_SIZE[1],
    )

    # 4. Verify Models
    print("\n--- Verifying Models ---")
    device = Config.DEVICE

    # Detector
    detector = KuzushijiDetector(pretrained=False).to(device)
    dummy_input = torch.randn(2, 3, 512, 512).to(
        device
    )  # Smaller input for quick check
    hm_out, wh_out, reg_out = detector(dummy_input)

    print(
        f"Detector Output Shapes -> HM: {hm_out.shape}, WH: {wh_out.shape}, Reg: {reg_out.shape}"
    )
    assert hm_out.shape == (2, 1, 128, 128)  # Stride 4
    assert wh_out.shape == (2, 2, 128, 128)

    # Classifier
    # Load class map generated by get_dataloaders
    class_map = np.load(Config.CLASS_MAP_PATH, allow_pickle=True).item()
    num_classes = len(class_map)
    print(f"Number of classes in mini dataset: {num_classes}")

    classifier = KuzushijiClassifier(num_classes=num_classes, pretrained=False).to(
        device
    )
    dummy_cls_input = torch.randn(4, 3, 64, 64).to(device)
    cls_out = classifier(dummy_cls_input)

    print(f"Classifier Output Shape: {cls_out.shape}")
    assert cls_out.shape == (4, num_classes)

    # 5. Training Loop Demo
    print("\n--- Running Training Demo (1 Epoch) ---")
    optimizer_det = torch.optim.Adam(detector.parameters(), lr=Config.DETECTOR_LR)
    optimizer_cls = torch.optim.Adam(classifier.parameters(), lr=Config.CLASSIFIER_LR)

    print("Training Detector...")
    detector = fit_detector(
        detector,
        loaders["detector_train"],
        loaders["detector_val"],
        optimizer_det,
        device,
        epochs=Config.DETECTOR_EPOCHS,
        patience=1,
    )

    print("Training Classifier...")
    classifier = fit_classifier(
        classifier,
        loaders["classifier_train"],
        loaders["classifier_val"],
        optimizer_cls,
        device,
        epochs=Config.CLASSIFIER_EPOCHS,
        patience=1,
    )

    # Verify weights exist
    assert os.path.exists(os.path.join(Config.WORKING_DIR, "detector_best.pth"))
    assert os.path.exists(os.path.join(Config.WORKING_DIR, "classifier_best.pth"))
    print("Model checkpoints saved successfully.")

    # 6. Metric Logic Verification
    print("\n--- Verifying Metric Logic ---")
    # Test Case:
    # GT: Label 'A' at box [10, 10, 20, 20] (x, y, w, h) -> Range x[10,30], y[10,30]
    # Pred 1: 'A' at (15, 15) -> TP
    # Pred 2: 'B' at (15, 15) -> FP (Wrong Label)
    # Pred 3: 'A' at (50, 50) -> FP (Outside Box)

    gt = [{"image_id": "img1", "gt": [("A", 10, 10, 20, 20)]}]
    preds = [
        {
            "image_id": "img1",
            "preds": [("A", 15, 15), ("B", 15, 15), ("A", 50, 50)],  # TP  # FP  # FP
        }
    ]

    scores = calc_modified_f1(preds, gt)
    print(f"Metric Check Results: {scores}")

    # Expected: 1 TP, 2 FP, 0 FN (GT was matched).
    # Precision = 1 / (1 + 2) = 0.33
    # Recall = 1 / (1 + 0) = 1.0
    assert scores["tp"] == 1
    assert scores["fp"] == 2
    assert scores["fn"] == 0
    assert abs(scores["precision"] - 0.3333333) < 1e-5

    # 7. Inference & Submission Demo
    print("\n--- Running Inference & Submission Demo ---")
    submission_path = os.path.join(Config.WORKING_DIR, "submission_demo.csv")

    generate_submission(
        test_metadata_path=Config.TEST_METADATA,
        detector_weights=os.path.join(Config.WORKING_DIR, "detector_best.pth"),
        classifier_weights=os.path.join(Config.WORKING_DIR, "classifier_best.pth"),
        output_csv=submission_path,
    )

    assert os.path.exists(submission_path)
    df_sub = pd.read_csv(submission_path)
    print(f"Submission generated with {len(df_sub)} rows.")
    print("Sample row:")
    print(df_sub.head(1))

    print("\n=== Demo Completed Successfully ===")


if __name__ == "__main__":
    main()
