import os
import torch
import pandas as pd
import numpy as np
import shutil
import warnings

# Import library modules
from library.config import Config
from library.utils import seed_everything
from library.data import prepare_train_val_loaders
from library.model import ResNet34FPN
from library.engine import train_model
from library.inference import generate_submission

# Suppress warnings for cleaner output
warnings.filterwarnings("ignore")


def main():
    print("=== Starting Demonstration Script ===")

    # 1. Setup Configuration for Demo
    # We override Config attributes to run a fast, lightweight demonstration.
    print("\n[1] Configuring environment...")

    # Create a separate working directory for this demo
    demo_dir = "./working/demo_execution"
    if os.path.exists(demo_dir):
        shutil.rmtree(demo_dir)
    os.makedirs(demo_dir, exist_ok=True)

    # Patch Config
    Config.WORKING_DIR = demo_dir
    Config.CHECKPOINT_PATH = os.path.join(demo_dir, "best_model.pth")
    Config.SUBMISSION_PATH = os.path.join(demo_dir, "submission.csv")

    # Reduce compute requirements for demo
    Config.EPOCHS = 1
    Config.BATCH_SIZE = 4
    Config.DEBUG = True  # This limits train/val data to 100/50 samples
    Config.NUM_WORKERS = 2  # Reduce workers for small debug batch

    print(f"Working Directory: {Config.WORKING_DIR}")
    print(f"Debug Mode: {Config.DEBUG}")
    print(f"Device: {Config.DEVICE}")

    # Set seeds
    seed_everything(Config.SEED)

    # 2. Data Loading & Verification
    print("\n[2] Preparing Data Loaders...")
    train_loader, val_loader = prepare_train_val_loaders(debug=Config.DEBUG)

    # Verify Train Loader
    print("Verifying data loader output...")
    images, masks, labels = next(iter(train_loader))

    print(
        f"Batch Shapes -> Images: {images.shape}, Masks: {masks.shape}, Labels: {labels.shape}"
    )

    # Assertions for Data
    # Images: (B, 3, H, W)
    assert images.shape == (
        Config.BATCH_SIZE,
        3,
        Config.IMG_SIZE,
        Config.IMG_SIZE,
    ), f"Image shape mismatch. Expected {(Config.BATCH_SIZE, 3, Config.IMG_SIZE, Config.IMG_SIZE)}, got {images.shape}"

    # Masks: (B, 1, H, W)
    assert masks.shape == (
        Config.BATCH_SIZE,
        1,
        Config.IMG_SIZE,
        Config.IMG_SIZE,
    ), f"Mask shape mismatch. Expected {(Config.BATCH_SIZE, 1, Config.IMG_SIZE, Config.IMG_SIZE)}, got {masks.shape}"

    # Labels: (B, 4) - 4 study classes
    assert labels.shape == (
        Config.BATCH_SIZE,
        4,
    ), f"Label shape mismatch. Expected {(Config.BATCH_SIZE, 4)}, got {labels.shape}"

    print("Data Loader verification successful.")

    # 3. Model Initialization & Verification
    print("\n[3] Initializing Model...")
    model = ResNet34FPN()
    model.to(Config.DEVICE)

    # Verify Forward Pass
    print("Verifying model forward pass...")
    images = images.to(Config.DEVICE)
    with torch.no_grad():
        cls_logits, seg_logits = model(images)

    print(f"Output Shapes -> Cls: {cls_logits.shape}, Seg: {seg_logits.shape}")

    # Assertions for Model Output
    # Classification: (B, 4)
    assert cls_logits.shape == (
        Config.BATCH_SIZE,
        4,
    ), "Classification logits shape mismatch."
    # Segmentation: (B, 1, H, W)
    assert seg_logits.shape == (
        Config.BATCH_SIZE,
        1,
        Config.IMG_SIZE,
        Config.IMG_SIZE,
    ), "Segmentation logits shape mismatch."

    print("Model verification successful.")

    # 4. Training Loop
    print("\n[4] Starting Training Loop (1 Epoch)...")

    optimizer = torch.optim.AdamW(
        model.parameters(), lr=Config.LEARNING_RATE, weight_decay=Config.WEIGHT_DECAY
    )

    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=Config.EPOCHS
    )

    # Train
    train_model(
        model,
        train_loader,
        val_loader,
        optimizer,
        scheduler,
        num_epochs=Config.EPOCHS,
        device=Config.DEVICE,
    )

    # Verify Checkpoint
    if not os.path.exists(Config.CHECKPOINT_PATH):
        # If mAP was 0.0 throughout (possible with random init and tiny debug data),
        # the engine might not have saved "best". Force save for inference demo.
        print(
            "Note: No improvement in mAP (expected in debug run). Saving current model for inference demo."
        )
        torch.save(model.state_dict(), Config.CHECKPOINT_PATH)

    assert os.path.exists(
        Config.CHECKPOINT_PATH
    ), "Model checkpoint file was not created."
    print(f"Checkpoint verified at {Config.CHECKPOINT_PATH}")

    # 5. Inference & Submission
    print("\n[5] Running Inference & Generating Submission...")

    # Config.TEST_CSV exists in metadata/test.csv (generated by metadata script)
    # generate_submission will load the model from Config.CHECKPOINT_PATH
    generate_submission(device=Config.DEVICE)

    # Verify Submission File
    assert os.path.exists(Config.SUBMISSION_PATH), "Submission file was not created."

    df_sub = pd.read_csv(Config.SUBMISSION_PATH)
    print(f"Submission loaded. Shape: {df_sub.shape}")

    # Check Columns
    assert (
        "Id" in df_sub.columns and "PredictionString" in df_sub.columns
    ), "Submission file missing required columns."

    # Check ID format (should contain _study or _image)
    sample_id = df_sub.iloc[0]["Id"]
    assert (
        "_study" in sample_id or "_image" in sample_id
    ), f"Unexpected ID format: {sample_id}"

    # Check Prediction String
    sample_pred = df_sub.iloc[0]["PredictionString"]
    assert isinstance(sample_pred, str), "PredictionString is not a string."

    print("Submission verification successful.")
    print("\n=== Demonstration Complete ===")


if __name__ == "__main__":
    main()
