import os
import sys
import pandas as pd
import numpy as np
import joblib
from sklearn.metrics import roc_auc_score
import warnings

# Add current directory to path to ensure library imports work
sys.path.append(os.getcwd())

# Import provided library modules
from library.config import Config
from library.utils import set_seed, setup_logger
from library.training_pipeline import TrainingPipeline
from library.inference_pipeline import InferencePipeline
from library.data_loader import load_union_dataset

# Suppress warnings for cleaner output
warnings.filterwarnings("ignore")


def main():
    # 1. Setup
    set_seed(Config.RANDOM_STATE)
    logger = setup_logger("runfile")
    logger.info("Starting Runfile Execution...")

    # 2. Training Phase
    # We run the full training pipeline.
    # debug_size=None ensures we use the full dataset for maximum performance,
    # as the dataset is small (~2.8k rows) and fits easily within time limits.
    pipeline = TrainingPipeline()
    pipeline.run(load_cached_data=True, debug_size=None)

    # 3. Validation Phase
    logger.info("Performing Validation on Hold-out Set...")

    # Reload the Union Dataset to map OOFs back to Request IDs
    # load_union_dataset is deterministic due to fixed random_state in Config
    union_df, _ = load_union_dataset(load_cached_data=True)

    # Load Level 1 OOF Predictions generated by the pipeline
    oof_path = os.path.join(Config.WORKING_DIR, "oof_predictions.csv")
    if not os.path.exists(oof_path):
        raise FileNotFoundError("OOF predictions not found. Training may have failed.")
    oof_df = pd.read_csv(oof_path)

    # Load the trained Meta-Learner
    meta_learner_path = os.path.join(Config.MODEL_DIR, "meta_learner.joblib")
    if not os.path.exists(meta_learner_path):
        raise FileNotFoundError("Meta-Learner model not found.")
    meta_learner = joblib.load(meta_learner_path)

    # Generate Level 2 Predictions (Meta-Model Probabilities) for the OOF data
    # We exclude the target column to get the feature matrix
    X_meta = oof_df.drop(columns=["target"]).values
    union_preds = meta_learner.predict_proba(X_meta)[:, 1]

    # Assign predictions back to the Union DataFrame
    union_df["final_pred"] = union_preds

    # Load the specific Validation Metadata to identify hold-out samples
    val_meta_path = Config.VAL_PATH
    val_meta_df = pd.read_parquet(val_meta_path)
    val_ids = set(val_meta_df[Config.ID_COL].values)

    # Filter Union DF to get only Validation rows
    val_results = union_df[union_df[Config.ID_COL].isin(val_ids)].copy()

    # Calculate Metric
    y_true = val_results[Config.TARGET_COL].values
    y_pred = val_results["final_pred"].values

    final_metric = roc_auc_score(y_true, y_pred)
    print(f"Final Validation Metric: {final_metric}")

    # 4. Failure Analysis
    logger.info("Performing Failure Analysis...")

    # Calculate Error (Absolute difference)
    val_results["error"] = np.abs(
        val_results[Config.TARGET_COL] - val_results["final_pred"]
    )

    # Select numeric columns for correlation analysis
    # We use the metadata columns defined in Config as they are the primary numeric inputs
    analysis_cols = Config.METADATA_COLS

    correlations = {}
    for col in analysis_cols:
        if col in val_results.columns:
            # Drop NaNs for correlation calculation
            valid_rows = val_results[[col, "error"]].dropna()
            if len(valid_rows) > 0:
                corr = valid_rows[col].corr(valid_rows["error"])
                correlations[col] = corr

    # Sort and print correlations
    sorted_corr = sorted(correlations.items(), key=lambda x: abs(x[1]), reverse=True)
    print("\nFailure Analysis - Correlation with Error:")
    for feature, corr in sorted_corr[:5]:
        print(f"  {feature}: {corr:.4f}")

    # 5. Submission
    THRESHOLD = 0.7222984867326668

    if final_metric > THRESHOLD:
        logger.info(
            f"Validation Metric ({final_metric}) > Threshold ({THRESHOLD}). Generating Submission..."
        )

        inference = InferencePipeline()
        inference.run(load_cached_data=True)

        # Verify submission exists
        if os.path.exists(Config.SUBMISSION_PATH):
            logger.info(f"Submission successfully saved to {Config.SUBMISSION_PATH}")
        else:
            logger.error("Submission file was not created.")
    else:
        logger.warning(
            f"Validation Metric ({final_metric}) did not meet threshold ({THRESHOLD}). Skipping submission."
        )


if __name__ == "__main__":
    main()
