import os
import shutil
import pandas as pd
import numpy as np
import warnings

# Import provided library classes
from library.feature_builder import MultiHypothesisFeaturizer
from library.model_engine import ResidualLGBMEnsemble

# Suppress warnings for cleaner output
warnings.filterwarnings("ignore")

# Constants
INPUT_DIR = "./input"
ORIGINAL_METADATA_DIR = "./metadata"
WORKING_DIR = "./working"
MINI_METADATA_DIR = os.path.join(WORKING_DIR, "mini_metadata")
CACHE_DIR = os.path.join(WORKING_DIR, "demo_cache")
SUBMISSION_PATH = os.path.join(WORKING_DIR, "demo_submission.csv")
SEED = 42


def setup_mini_metadata():
    """
    Creates a subset of metadata to limit the amount of raw data processed.
    This ensures the demo runs quickly by only processing a few drives.
    """
    print("Setting up mini metadata for rapid demonstration...")
    os.makedirs(MINI_METADATA_DIR, exist_ok=True)

    # 1. Create Mini Train Metadata
    train_meta_path = os.path.join(ORIGINAL_METADATA_DIR, "train_metadata.csv")
    if os.path.exists(train_meta_path):
        df_train = pd.read_csv(train_meta_path)
        # Select 2 unique drives for training to allow GroupKFold with n_folds=2
        train_drives = df_train["drive_id"].unique()[:2]
        df_train_mini = df_train[df_train["drive_id"].isin(train_drives)].copy()
        # Limit rows per drive to speed up feature calculation
        df_train_mini = (
            df_train_mini.groupby("drive_id").head(100).reset_index(drop=True)
        )

        df_train_mini.to_csv(
            os.path.join(MINI_METADATA_DIR, "train_metadata.csv"), index=False
        )
        print(
            f"  Created mini train metadata: {len(df_train_mini)} rows from drives {train_drives}"
        )

    # 2. Create Mini Val Metadata
    val_meta_path = os.path.join(ORIGINAL_METADATA_DIR, "val_metadata.csv")
    if os.path.exists(val_meta_path):
        df_val = pd.read_csv(val_meta_path)
        # Select 1 drive for validation
        val_drives = df_val["drive_id"].unique()[:1]
        df_val_mini = df_val[df_val["drive_id"].isin(val_drives)].copy()
        df_val_mini = df_val_mini.head(100).reset_index(drop=True)

        df_val_mini.to_csv(
            os.path.join(MINI_METADATA_DIR, "val_metadata.csv"), index=False
        )
        print(
            f"  Created mini val metadata: {len(df_val_mini)} rows from drives {val_drives}"
        )

    # 3. Create Mini Test Metadata
    test_meta_path = os.path.join(ORIGINAL_METADATA_DIR, "test_metadata.csv")
    if os.path.exists(test_meta_path):
        df_test = pd.read_csv(test_meta_path)
        # Select 1 drive for testing
        test_drives = df_test["drive_id"].unique()[:1]
        df_test_mini = df_test[df_test["drive_id"].isin(test_drives)].copy()
        df_test_mini = df_test_mini.head(20).reset_index(drop=True)

        df_test_mini.to_csv(
            os.path.join(MINI_METADATA_DIR, "test_metadata.csv"), index=False
        )
        print(
            f"  Created mini test metadata: {len(df_test_mini)} rows from drives {test_drives}"
        )


def run_pipeline():
    # --- Step 1: Initialize Featurizer ---
    # We point it to our mini metadata directory to load only the subset of data
    print("\n--- Initializing Feature Builder ---")
    featurizer = MultiHypothesisFeaturizer(
        input_dir=INPUT_DIR, metadata_dir=MINI_METADATA_DIR, cache_dir=CACHE_DIR
    )

    # --- Step 2: Load and Process Data ---
    # This calls DataManager internally, which processes GNSS/IMU files
    # load_cached_data=False forces re-processing from raw files
    print("\n--- Loading and Featurizing Data ---")
    train_df, val_df = featurizer.get_train_data(load_cached_data=False)
    test_df = featurizer.get_test_data(load_cached_data=False)

    # Validate data loading
    assert not train_df.empty, "Training data should not be empty"
    assert not val_df.empty, "Validation data should not be empty"
    assert not test_df.empty, "Test data should not be empty"

    # Check for physics-based features generated by gnss_math.py
    expected_features = ["newton_E_sig", "newton_N_sig", "newton_U_sig", "GDOP", "PDOP"]
    for feat in expected_features:
        assert feat in train_df.columns, f"Feature {feat} missing from training data"

    # Check for targets computed by DataManager
    expected_targets = ["target_E", "target_N", "target_U"]
    for target in expected_targets:
        assert target in train_df.columns, f"Target {target} missing from training data"

    print(f"Training Features: {train_df.shape[1]}")
    print(f"Feature Columns: {featurizer.get_feature_names()[:5]} ...")

    # --- Step 3: Train Model Ensemble ---
    print("\n--- Training LightGBM Ensemble ---")

    # Combine train and val for cross-validation demonstration
    # In a real scenario, we might keep them separate or use the val set for final scoring
    full_train_df = pd.concat([train_df, val_df], ignore_index=True)

    model_engine = ResidualLGBMEnsemble(
        output_dir=os.path.join(CACHE_DIR, "models"),
        n_folds=2,  # Minimal folds for speed
        seed=SEED,
    )

    # Hyperparameters optimized for speed
    lgbm_params = {
        "objective": "regression_l1",
        "metric": "mae",
        "boosting_type": "gbdt",
        "learning_rate": 0.1,
        "num_leaves": 10,
        "max_depth": 3,
        "feature_fraction": 0.8,
        "bagging_fraction": 0.8,
        "bagging_freq": 1,
        "min_data_in_leaf": 5,
        "n_jobs": 4,
        "verbose": -1,
        "seed": SEED,
    }

    scores = model_engine.train_group_kfold(
        train_df=full_train_df,
        feature_cols=featurizer.get_feature_names(),
        target_cols=featurizer.get_target_names(),
        params=lgbm_params,
        n_estimators=20,  # Very few trees for demo
        early_stopping_rounds=5,
    )

    # Validate scores dictionary
    for target in expected_targets:
        assert target in scores, f"Score for {target} missing"
        print(f"Final CV Score for {target}: {scores[target]:.4f}")

    # --- Step 4: Generate Predictions ---
    print("\n--- Generating Predictions ---")

    # The predict_ensemble method handles the conversion from predicted ENU residuals
    # back to absolute Latitude/Longitude using the WLS baseline.
    submission_df = model_engine.predict_ensemble(
        test_df=test_df,
        feature_cols=featurizer.get_feature_names(),
        target_cols=featurizer.get_target_names(),
        submission_path=SUBMISSION_PATH,
    )

    # --- Step 5: Verification ---
    print("\n--- Verifying Submission ---")

    # Check file existence
    if not os.path.exists(SUBMISSION_PATH):
        raise FileNotFoundError("Submission file was not created.")

    # Check columns
    required_cols = ["tripId", "UnixTimeMillis", "LatitudeDegrees", "LongitudeDegrees"]
    if not all(col in submission_df.columns for col in required_cols):
        raise ValueError(
            f"Submission missing required columns. Found: {submission_df.columns}"
        )

    # Check row count matches input test metadata
    if len(submission_df) != len(test_df):
        raise ValueError(
            f"Submission row count mismatch. Expected {len(test_df)}, got {len(submission_df)}"
        )

    # Check for NaN values
    if submission_df.isnull().any().any():
        raise ValueError("Submission contains NaN values.")

    # Basic sanity check on coordinates (MTV area is roughly 37.4, -122.0)
    lat_mean = submission_df["LatitudeDegrees"].mean()
    lon_mean = submission_df["LongitudeDegrees"].mean()
    print(f"Mean Predicted Lat: {lat_mean:.4f}")
    print(f"Mean Predicted Lon: {lon_mean:.4f}")

    # Assert reasonable bounds for Mountain View / San Jose area (roughly)
    # This is just a loose check to ensure coordinate conversion didn't explode
    assert 30 < lat_mean < 45, "Latitude prediction out of bounds"
    assert -130 < lon_mean < -110, "Longitude prediction out of bounds"

    print("\nPipeline demonstration completed successfully!")


if __name__ == "__main__":
    # Clean up previous run
    if os.path.exists(WORKING_DIR):
        shutil.rmtree(WORKING_DIR)
    os.makedirs(WORKING_DIR, exist_ok=True)

    try:
        setup_mini_metadata()
        run_pipeline()
    except Exception as e:
        print(f"\nPipeline failed with error: {e}")
        raise e
