import os
import torch
import numpy as np
import pandas as pd
import shutil

# Import from the provided library
from library.config import DEVICE, Z_DIM, PATCH_SIZE, SUBMISSION_FILE, CACHE_DIR
from library.utils import set_seed, fbeta_score, rle_encoding
from library.data import get_dataloaders
from library.model import DepthProjectionCNN
from library.train import run_training
from library.inference import predict_fragment, generate_submission_file


def main():
    print("=== Starting Demonstration Script ===")

    # 1. Setup Reproducibility
    set_seed(42)
    print("Random seed set to 42.")

    # Clean up working directory for a fresh run
    if os.path.exists(CACHE_DIR):
        shutil.rmtree(CACHE_DIR)
    if os.path.exists(SUBMISSION_FILE):
        os.remove(SUBMISSION_FILE)

    # 2. Verify Utility Functions
    print("\n--- Verifying Utilities (library.utils) ---")

    # Test RLE Encoding
    # Create a simple mask: 0 0 1 1 1 0 0 1 0
    # 1-based indices:     1 2 3 4 5 6 7 8 9
    # Runs: Start 3, Len 3; Start 8, Len 1
    dummy_mask = np.array([[0, 0, 1], [1, 1, 0], [0, 1, 0]], dtype=np.uint8)
    # Flattened: 0 0 1 1 1 0 0 1 0
    expected_rle = "3 3 8 1"
    calculated_rle = rle_encoding(dummy_mask)
    assert (
        calculated_rle == expected_rle
    ), f"RLE mismatch. Expected '{expected_rle}', got '{calculated_rle}'"
    print("RLE Encoding verified.")

    # Test F-Beta Score
    # Preds: 0.8 (TP), 0.2 (TN), 0.9 (FP), 0.1 (FN) -> Threshold 0.5
    # Targets: 1, 0, 0, 1
    # TP=1, FP=1, FN=1
    # Beta=0.5 -> Weight Precision higher
    dummy_preds = torch.tensor([0.8, 0.2, 0.9, 0.1])
    dummy_targets = torch.tensor([1.0, 0.0, 0.0, 1.0])
    score = fbeta_score(dummy_preds, dummy_targets, beta=0.5, threshold=0.5)

    # Calculation:
    # Precision = 1 / (1+1) = 0.5
    # Recall = 1 / (1+1) = 0.5
    # F0.5 = (1 + 0.25) * 0.5 * 0.5 / (0.25 * 0.5 + 0.5) = 1.25 * 0.25 / 0.625 = 0.3125 / 0.625 = 0.5
    assert np.isclose(score, 0.5), f"F-Beta Score mismatch. Expected 0.5, got {score}"
    print("F-Beta Score verified.")

    # 3. Verify Data Loading
    print("\n--- Verifying Data Loading (library.data) ---")
    # We limit samples to 16 to ensure preprocessing is fast
    batch_size = 4
    dataloaders = get_dataloaders(
        batch_size=batch_size,
        limit_samples=16,
        load_cached_data=False,  # Force processing to demonstrate it works
    )

    assert "train" in dataloaders, "Train dataloader missing"
    assert "val" in dataloaders, "Val dataloader missing"
    assert "test" in dataloaders, "Test dataloader missing"

    # Check Train Batch
    train_loader = dataloaders["train"]
    inputs, targets = next(iter(train_loader))

    print(f"Train Batch Input Shape: {inputs.shape}")
    print(f"Train Batch Target Shape: {targets.shape}")

    # Expected: (Batch, Z_DIM, H, W) and (Batch, 1, H, W)
    assert inputs.shape == (
        batch_size,
        Z_DIM,
        PATCH_SIZE,
        PATCH_SIZE,
    ), f"Incorrect input shape: {inputs.shape}"
    assert targets.shape == (
        batch_size,
        1,
        PATCH_SIZE,
        PATCH_SIZE,
    ), f"Incorrect target shape: {targets.shape}"
    assert inputs.dtype == torch.float32, "Input should be float32"

    print("Data loading verified.")

    # 4. Verify Model Architecture
    print("\n--- Verifying Model (library.model) ---")
    model = DepthProjectionCNN(in_channels=Z_DIM).to(DEVICE)

    # Forward pass with the batch fetched earlier
    inputs = inputs.to(DEVICE)
    with torch.no_grad():
        logits = model(inputs)

    print(f"Model Output Shape: {logits.shape}")
    assert logits.shape == (
        batch_size,
        1,
        PATCH_SIZE,
        PATCH_SIZE,
    ), f"Output shape mismatch. Expected {(batch_size, 1, PATCH_SIZE, PATCH_SIZE)}, got {logits.shape}"
    print("Model architecture verified.")

    # 5. Verify Training Pipeline
    print("\n--- Verifying Training Pipeline (library.train) ---")
    # Running a very short training loop (1 epoch)
    # This also implicitly tests predict_and_submit from library.model
    trained_model = run_training(
        epochs=1,
        batch_size=4,
        limit_samples=16,
        load_cached_data=True,  # Use the cache generated in step 3
        patience=1,
    )

    assert os.path.exists(
        os.path.join(CACHE_DIR, "best_model.pth")
    ), "best_model.pth was not saved."
    assert os.path.exists(
        SUBMISSION_FILE
    ), "submission.csv was not generated by run_training."
    print("Training pipeline executed successfully.")

    # 6. Verify Inference Module Explicitly
    print("\n--- Verifying Inference Module (library.inference) ---")
    # Although run_training generated a submission, we want to explicitly test
    # the functions in library.inference to ensure full coverage.

    # Test predict_fragment
    test_loader = dataloaders["test"]
    fragment_maps = predict_fragment(trained_model, test_loader, device=DEVICE)

    assert isinstance(
        fragment_maps, dict
    ), "predict_fragment should return a dictionary"
    assert len(fragment_maps) > 0, "No fragments processed"

    # Check map properties
    fid = list(fragment_maps.keys())[0]
    prob_map = fragment_maps[fid]
    assert isinstance(prob_map, np.ndarray), "Probability map should be numpy array"
    assert prob_map.ndim == 2, "Probability map should be 2D"
    print(f"Inference generated map for fragment '{fid}' with shape {prob_map.shape}")

    # Test generate_submission_file
    # We'll save to a different file to distinguish from the one generated by run_training
    manual_sub_file = "./working/manual_submission.csv"
    generate_submission_file(
        fragment_maps, threshold=0.5, submission_path=manual_sub_file
    )

    assert os.path.exists(manual_sub_file), "Manual submission file not created"

    # Verify content format
    df_sub = pd.read_csv(manual_sub_file)
    assert list(df_sub.columns) == ["Id", "Predicted"], "Submission columns mismatch"
    assert len(df_sub) == len(fragment_maps), "Row count mismatch in submission"
    print("Inference module verified.")

    print("\n=== All Demonstrations Completed Successfully ===")


if __name__ == "__main__":
    main()
