import os
import torch
import pandas as pd
import numpy as np
import transformers
from transformers import AutoTokenizer, get_cosine_schedule_with_warmup

# Import provided library modules
from library.config import Config
from library.utils import seed_everything
from library.model import TweetModel, decode_prediction
from library.data import get_loaders
from library.engine import train_fn, eval_fn, predict_fn


def run_demo():
    # Suppress verbose output from transformers
    transformers.logging.set_verbosity_error()

    print("=== Starting Self-Contained Demo Script ===")

    # 1. Configuration Overrides for Speed and Demo Purposes
    print("\n[1] Configuring environment...")
    Config.DEBUG = True
    Config.DEBUG_SAMPLE_SIZE = 60  # Small subset for speed
    Config.TRAIN_BATCH_SIZE = 8
    Config.VALID_BATCH_SIZE = 8
    Config.EPOCHS = 1
    Config.NUM_WORKERS = 0  # Disable multiprocessing for simple demo stability

    # Set seed for reproducibility
    seed_everything(Config.SEED)
    print("    Configuration set: DEBUG=True, Epochs=1, Batch Size=8")

    # 2. Data Loading and Processing
    print("\n[2] Preparing DataLoaders...")
    tokenizer = AutoTokenizer.from_pretrained(Config.MODEL_PATH)

    # We set load_cached_data=False to force the processing logic to run and generate cache files
    # which we will need to read explicitly later for evaluation alignment.
    train_loader, val_loader, test_loader = get_loaders(
        tokenizer=tokenizer,
        batch_size=Config.TRAIN_BATCH_SIZE,
        load_cached_data=False,
        debug=Config.DEBUG,
    )

    print(f"    Train Batches: {len(train_loader)}")
    print(f"    Val Batches:   {len(val_loader)}")
    print(f"    Test Batches:  {len(test_loader)}")

    # Verify Data Integrity
    sample_batch = next(iter(train_loader))
    assert "input_ids" in sample_batch
    assert "attention_mask" in sample_batch
    assert "start_labels" in sample_batch
    assert "end_labels" in sample_batch
    print("    Data integrity verified.")

    # 3. Model Initialization
    print("\n[3] Initializing Model...")
    model = TweetModel()
    model.to(Config.DEVICE)

    # Verify Forward Pass
    with torch.no_grad():
        input_ids = sample_batch["input_ids"].to(Config.DEVICE)
        mask = sample_batch["attention_mask"].to(Config.DEVICE)
        s_logits, e_logits = model(input_ids, mask)

    assert s_logits.shape == (
        input_ids.shape[0],
        Config.MAX_LEN,
    ), "Start logits shape mismatch"
    assert e_logits.shape == (
        input_ids.shape[0],
        Config.MAX_LEN,
    ), "End logits shape mismatch"
    print("    Model forward pass verified.")

    # 4. Training Loop Simulation
    print("\n[4] Running Training Loop (1 Epoch)...")
    optimizer = torch.optim.AdamW(model.parameters(), lr=Config.LEARNING_RATE)
    # Simple scheduler for the demo
    scheduler = get_cosine_schedule_with_warmup(
        optimizer, num_warmup_steps=0, num_training_steps=len(train_loader)
    )

    train_loss = train_fn(train_loader, model, optimizer, Config.DEVICE, scheduler)
    print(f"    Training finished. Average Loss: {train_loss:.4f}")

    if np.isnan(train_loss):
        raise ValueError("Training loss is NaN.")

    # 5. Evaluation with Metric Calculation
    print("\n[5] Running Evaluation...")

    # To run eval_fn, we need the validation dataframe and the token offsets.
    # get_loaders processes the data and saves it to cache. We need to load that specific cache
    # to ensure our dataframe aligns with the tensors in val_loader.

    # 5a. Reconstruct the filtered validation dataframe
    df_val = pd.read_csv(Config.VAL_FILE)
    if Config.DEBUG:
        df_val = df_val.head(Config.DEBUG_SAMPLE_SIZE)
    # Filter neutrals as done in library/data.py
    df_val = df_val[df_val["sentiment"] != "neutral"].reset_index(drop=True)

    # 5b. Load the valid indices and offsets generated by process_data
    # Cache name logic from library/data.py: f"val_fixed_no_neutral{suffix}"
    cache_name = "val_fixed_no_neutral_debug"

    valid_idx_path = os.path.join(Config.WORKING_DIR, f"{cache_name}_valid_idx.npy")
    offsets_path = os.path.join(Config.WORKING_DIR, f"{cache_name}_offsets.npy")

    if not os.path.exists(valid_idx_path) or not os.path.exists(offsets_path):
        raise FileNotFoundError("Cache files not found. process_data execution failed?")

    valid_indices = np.load(valid_idx_path)
    val_offsets = np.load(offsets_path)

    # Align dataframe with processed data (some rows might be dropped due to alignment issues)
    df_val = df_val.iloc[valid_indices].reset_index(drop=True)

    assert len(df_val) == len(
        val_offsets
    ), "Mismatch between validation dataframe and offsets"
    assert len(df_val) == len(
        val_loader.dataset
    ), "Mismatch between validation dataframe and dataset"

    # 5c. Run Evaluation
    val_loss, val_jaccard = eval_fn(
        val_loader, model, Config.DEVICE, df_val, val_offsets
    )
    print(
        f"    Evaluation finished. Loss: {val_loss:.4f}, Jaccard Score: {val_jaccard:.4f}"
    )

    # 6. Inference on Test Set
    print("\n[6] Running Inference on Test Set...")

    # 6a. Reconstruct Test Dataframe (Test set is not filtered for neutrals in data.py, just processed)
    df_test = pd.read_csv(Config.TEST_FILE)
    if Config.DEBUG:
        df_test = df_test.head(Config.DEBUG_SAMPLE_SIZE)

    # 6b. Load Test Offsets
    test_cache_name = "test_fixed_debug"
    test_offsets_path = os.path.join(
        Config.WORKING_DIR, f"{test_cache_name}_offsets.npy"
    )
    test_offsets = np.load(test_offsets_path)

    # 6c. Get Predictions
    s_logits, e_logits = predict_fn(test_loader, model, Config.DEVICE)

    # 6d. Decode a sample prediction
    # Convert logits to probabilities
    s_probs = np.exp(s_logits) / np.sum(np.exp(s_logits), axis=-1, keepdims=True)
    e_probs = np.exp(e_logits) / np.sum(np.exp(e_logits), axis=-1, keepdims=True)

    # Pick the first sample
    idx = 0
    text = str(df_test.iloc[idx]["text"])
    sentiment = df_test.iloc[idx]["sentiment"]
    offsets = test_offsets[idx]

    pred_span = decode_prediction(s_probs[idx], e_probs[idx], text, offsets, sentiment)

    print(f"    Sample Test Case:")
    print(f"      Text: '{text}'")
    print(f"      Sentiment: {sentiment}")
    print(f"      Predicted Span: '{pred_span}'")

    # Final assertion to ensure output is a string
    assert isinstance(pred_span, str), "Prediction must be a string"

    print("\n=== Demo Completed Successfully ===")


if __name__ == "__main__":
    run_demo()
