import os
import sys
import torch
import pandas as pd
import numpy as np
from torch.utils.data import DataLoader
from scipy.stats import pearsonr

# Import library components
from library.config import Config
from library.train import train_model
from library.inference import inference_fn
from library.dataset import get_processed_dataframe, UWMapDataset
from library.model import UnetPlusPlus
from library.utils import (
    set_seed,
    dice_coef,
    hausdorff_distance_3d,
    keep_largest_component_3d,
)


def run_validation_and_analysis():
    """
    Runs validation on the hold-out set using the best saved model.
    Computes the final metric and performs failure analysis.
    """
    print("\n=== Running Final Validation & Failure Analysis ===")
    device = torch.device(Config.DEVICE)

    # Load Validation Data
    # We use the validation metadata generated by the metadata script
    df_val = get_processed_dataframe(Config.VAL_METADATA_PATH, split_name="val")

    # Dataset and Loader
    # Validation mode uses standard resizing to Config.IMG_SIZE (512)
    val_dataset = UWMapDataset(df_val, mode="val", img_size=Config.IMG_SIZE)
    val_loader = DataLoader(
        val_dataset,
        batch_size=Config.BATCH_SIZE,
        shuffle=False,
        num_workers=Config.NUM_WORKERS,
        pin_memory=True,
    )

    # Load Model
    model = UnetPlusPlus().to(device)
    weights_path = os.path.join(Config.WORKING_DIR, "best_model.pth")

    if os.path.exists(weights_path):
        print(f"Loading best model weights from {weights_path}")
        model.load_state_dict(torch.load(weights_path, map_location=device))
    else:
        print(
            "WARNING: Best model weights not found. Using random initialization (Score will be low)."
        )

    model.eval()

    # Storage for predictions and ground truth
    # We group by 'scan_id' which is a combination of case and day
    # to ensure we construct 3D volumes correctly.
    val_preds_map = {}
    val_gt_map = {}
    scan_metadata = {}

    print("Generating predictions on validation set...")
    with torch.no_grad():
        for batch_idx, (images, masks) in enumerate(val_loader):
            images = images.to(device)

            # Inference
            outputs = model(images)
            preds = torch.sigmoid(outputs)

            preds_np = preds.cpu().numpy()
            masks_np = masks.numpy()

            # Map back to metadata
            start_idx = batch_idx * Config.BATCH_SIZE
            end_idx = start_idx + images.size(0)
            batch_rows = df_val.iloc[start_idx:end_idx]

            for i, (_, row) in enumerate(batch_rows.iterrows()):
                case_id = row["case"]
                day_id = row["day"]
                # Unique scan identifier
                scan_id = f"{case_id}_{day_id}"
                slice_idx = row["slice"]

                if scan_id not in val_preds_map:
                    val_preds_map[scan_id] = {0: [], 1: [], 2: []}
                    val_gt_map[scan_id] = {0: [], 1: [], 2: []}
                    scan_metadata[scan_id] = {
                        "day": day_id,
                        "pixel_spacing_w": row["pixel_spacing_w"],
                        "img_width": row["img_width"],
                    }

                for c in range(Config.NUM_CLASSES):
                    # Thresholding
                    p_slice = (preds_np[i, c] > Config.THRESHOLD).astype(np.uint8)
                    g_slice = masks_np[i, c].astype(np.uint8)

                    val_preds_map[scan_id][c].append((slice_idx, p_slice))
                    val_gt_map[scan_id][c].append((slice_idx, g_slice))

    print("Computing 3D Metrics per scan...")
    scan_scores = []

    # Data for failure analysis
    error_magnitudes = []
    feat_days = []
    feat_spacings = []
    feat_widths = []

    for scan_id in val_preds_map:
        scan_dices = []
        scan_hds = []

        for c in range(Config.NUM_CLASSES):
            # Sort slices by Z-index
            p_list = sorted(val_preds_map[scan_id][c], key=lambda x: x[0])
            g_list = sorted(val_gt_map[scan_id][c], key=lambda x: x[0])

            # Stack to 3D Volume (D, H, W)
            vol_pred = np.stack([x[1] for x in p_list], axis=0)
            vol_gt = np.stack([x[1] for x in g_list], axis=0)

            # Post-processing: Keep largest connected component
            vol_pred = keep_largest_component_3d(vol_pred)

            # Calculate Metrics
            d = dice_coef(vol_gt, vol_pred)
            h = hausdorff_distance_3d(vol_gt, vol_pred)

            scan_dices.append(d)
            scan_hds.append(h)

        # Average over classes for this scan
        mean_scan_dice = np.mean(scan_dices)
        mean_scan_hd = np.mean(scan_hds)

        # Combined Score: 0.4*Dice + 0.6*(1-HD)
        scan_score = (0.4 * mean_scan_dice) + (0.6 * (1.0 - mean_scan_hd))
        scan_scores.append(scan_score)

        # Collect data for failure analysis
        error_magnitudes.append(1.0 - scan_score)
        meta = scan_metadata[scan_id]
        feat_days.append(meta["day"])
        feat_spacings.append(meta["pixel_spacing_w"])
        feat_widths.append(meta["img_width"])

    final_metric = np.mean(scan_scores)

    # Print required output
    print(f"Final Validation Metric: {final_metric}")

    # Failure Analysis
    print("\n--- Failure Analysis (Correlation with Error Magnitude) ---")
    if len(error_magnitudes) > 5:
        # Avoid warnings with constant inputs
        if np.std(feat_days) > 0:
            corr_day, _ = pearsonr(error_magnitudes, feat_days)
            print(f"Correlation with Day: {corr_day:.4f}")
        else:
            print("Correlation with Day: N/A (Constant)")

        if np.std(feat_spacings) > 0:
            corr_spacing, _ = pearsonr(error_magnitudes, feat_spacings)
            print(f"Correlation with Pixel Spacing: {corr_spacing:.4f}")
        else:
            print("Correlation with Pixel Spacing: N/A (Constant)")

        if np.std(feat_widths) > 0:
            corr_width, _ = pearsonr(error_magnitudes, feat_widths)
            print(f"Correlation with Image Width: {corr_width:.4f}")
        else:
            print("Correlation with Image Width: N/A (Constant)")
    else:
        print("Insufficient samples for failure analysis.")

    return final_metric


def main():
    # 1. Setup and Configuration
    Config.setup()
    set_seed(Config.SEED)

    # Override Config for Fast Baseline
    # Reduce epochs to ensure completion within 2 hours
    Config.EPOCHS = 5
    # Use smaller scales during training for speed, while keeping 512 for inference
    Config.IMG_SCALES = [320, 384, 448]

    print(
        f"Running Fast Baseline with Config: Epochs={Config.EPOCHS}, Scales={Config.IMG_SCALES}"
    )

    # 2. Train Model
    # debug=False ensures we train on the full dataset (balanced), but for fewer epochs
    train_model(debug=False)

    # 3. Validation and Analysis
    metric = run_validation_and_analysis()

    # 4. Submission
    # Threshold defined in task
    SUBMISSION_THRESHOLD = 0.438

    if metric > SUBMISSION_THRESHOLD:
        print(
            f"\nMetric {metric:.6f} exceeds threshold {SUBMISSION_THRESHOLD}. Generating submission..."
        )
        inference_fn(debug=False)
    else:
        print(
            f"\nMetric {metric:.6f} does not exceed threshold {SUBMISSION_THRESHOLD}. Submission skipped."
        )


if __name__ == "__main__":
    main()
