import os
import shutil
import numpy as np
import pandas as pd
import warnings

# Import from the provided library
from library.config import WORKING_DIR, RANDOM_SEED
from library.features import load_train_data, load_val_data, load_test_data
from library.model import StratifiedEnsemble
from library.metrics import calculate_log_mae

# Suppress warnings for cleaner output
warnings.filterwarnings("ignore")


def main():
    # -------------------------------------------------------------------------
    # 1. Setup and Cache Management
    # -------------------------------------------------------------------------
    print("Initializing Demonstration...")

    # The provided working directory information indicates cache files exist in 'idea_1',
    # but config.py points WORKING_DIR to 'idea_2'. We skip copying them because
    # the cached files are stale (missing new features like cos_mean_0).
    # This forces the pipeline to regenerate features from scratch.
    os.makedirs(WORKING_DIR, exist_ok=True)

    # -------------------------------------------------------------------------
    # 2. Data Loading
    # -------------------------------------------------------------------------
    print("\nLoading Data...")
    # These functions will now pick up the parquet files we just copied
    # If cache is missing, it will process from scratch (which is handled by the library)
    df_train_full = load_train_data(load_cached_data=True)
    df_val_full = load_val_data(load_cached_data=True)

    # Verify data integrity
    assert not df_train_full.empty, "Training data is empty!"
    assert not df_val_full.empty, "Validation data is empty!"

    # -------------------------------------------------------------------------
    # 3. Subsampling for Speed
    # -------------------------------------------------------------------------
    # We use a small subset to demonstrate the pipeline quickly.
    # Training on the full 3M+ dataset would take too long for this demo.
    N_TRAIN = 5000
    N_VAL = 1000

    df_train = df_train_full.sample(
        n=min(N_TRAIN, len(df_train_full)), random_state=RANDOM_SEED
    ).copy()
    df_val = df_val_full.sample(
        n=min(N_VAL, len(df_val_full)), random_state=RANDOM_SEED
    ).copy()

    print(f"  Subsampled Train Shape: {df_train.shape}")
    print(f"  Subsampled Val Shape: {df_val.shape}")

    # -------------------------------------------------------------------------
    # 4. Feature Verification
    # -------------------------------------------------------------------------
    print("\nVerifying Features...")
    # Check if feature engineering (angular, topological) worked as expected
    # These columns are generated by library.features.process_data
    expected_cols = ["dist", "dist_inv2", "cos_mean_0", "n_C_0", "degree_1"]
    for col in expected_cols:
        assert col in df_train.columns, f"Missing expected feature: {col}"

    print("  All expected feature columns are present.")

    # -------------------------------------------------------------------------
    # 5. Model Initialization (StratifiedEnsemble)
    # -------------------------------------------------------------------------
    # Define fast hyperparameters for demonstration.
    # The default config has 25,000 estimators which is too slow for a quick run.
    fast_params = {
        "n_estimators": 20,  # Very low for speed
        "learning_rate": 0.1,
        "max_depth": 4,
        "objective": "reg:absoluteerror",
        "n_jobs": 4,
        "tree_method": "hist",
        "random_state": RANDOM_SEED,
        "subsample": 0.8,
        "colsample_bytree": 0.8,
        "device": "cpu",  # Force CPU for small data to avoid overhead, or use 'cuda' if preferred
    }

    print("\nInitializing StratifiedEnsemble with fast parameters...")
    model = StratifiedEnsemble(params=fast_params)

    # -------------------------------------------------------------------------
    # 6. Training
    # -------------------------------------------------------------------------
    print("Fitting model (this may take a moment)...")
    # The fit method handles stratification by coupling type automatically
    model.fit(
        X_train=df_train,
        y_train=df_train["scalar_coupling_constant"],
        groups_train=df_train["type"],
        X_val=df_val,
        y_val=df_val["scalar_coupling_constant"],
        groups_val=df_val["type"],
        verbose=False,  # Suppress XGBoost logs for cleaner output
    )

    # Verify models were created for types present in training data
    present_types = df_train["type"].unique()
    for t in present_types:
        # We only check for standard types defined in config
        if t in ["1JHC", "1JHN", "2JHC", "2JHH", "2JHN", "3JHC", "3JHH", "3JHN"]:
            assert t in model.models, f"Model for type {t} was not trained!"
    print(f"  Successfully trained models for {len(model.models)} coupling types.")

    # -------------------------------------------------------------------------
    # 7. Prediction and Evaluation
    # -------------------------------------------------------------------------
    print("\nPredicting on Validation Set...")
    val_preds = model.predict(df_val, df_val["type"])

    # Assert predictions are not NaN
    assert not val_preds.isnull().any(), "Predictions contain NaNs!"

    # Calculate Metric using the library function
    score = calculate_log_mae(
        df_val["scalar_coupling_constant"], val_preds, df_val["type"]
    )
    print(f"  Validation LogMAE (Calculated): {score:.5f}")

    # -------------------------------------------------------------------------
    # 8. Model Persistence (Save/Load)
    # -------------------------------------------------------------------------
    print("\nTesting Model Persistence...")
    save_dir = os.path.join(WORKING_DIR, "demo_model")
    model.save_models(save_dir)

    # Load into a new instance
    loaded_model = StratifiedEnsemble(params=fast_params)
    loaded_model.load_models(save_dir)

    # Verify predictions match
    loaded_preds = loaded_model.predict(df_val, df_val["type"])
    np.testing.assert_allclose(
        val_preds,
        loaded_preds,
        err_msg="Loaded model predictions do not match original!",
    )
    print("  Persistence check passed: Loaded model reproduces predictions exactly.")

    # -------------------------------------------------------------------------
    # 9. Inference on Test Data
    # -------------------------------------------------------------------------
    print("\nRunning Inference on Test Data (Subset)...")
    df_test_full = load_test_data(load_cached_data=True)
    df_test = df_test_full.sample(
        n=min(1000, len(df_test_full)), random_state=RANDOM_SEED
    ).copy()

    # Predict
    test_preds = loaded_model.predict(df_test, df_test["type"])

    # Create submission dataframe
    submission = pd.DataFrame(
        {"id": df_test["id"], "scalar_coupling_constant": test_preds}
    )

    print("  Sample Submission Head:")
    print(submission.head().to_string(index=False))

    print("\nDemonstration Completed Successfully.")


if __name__ == "__main__":
    main()
