import os
import sys
import numpy as np
import pandas as pd
import warnings

# Add the current directory to path to ensure library imports work
sys.path.append(os.getcwd())

from library.config import SEED, MODEL_OUTPUT_DIR
from library.training_pipeline import TrainingPipeline
from library.inference import InferencePipeline
from library.data_factory import DataFactory
from library.model_factory import EnsemblePredictor
from library.utils import set_seed, compute_mcc

# Suppress warnings
warnings.filterwarnings("ignore")
os.environ["PYTHONWARNINGS"] = "ignore"


def run_failure_analysis(df_val, preds_prob):
    """
    Performs failure analysis by correlating error magnitude with features.
    """
    print("\n--- Failure Analysis ---")

    y_val = df_val["contact"].values
    # Calculate error magnitude (absolute difference between truth and probability)
    errors = np.abs(y_val - preds_prob)

    # Select numeric feature columns
    # Exclude metadata and target
    meta_cols = [
        "contact_id",
        "game_play",
        "step",
        "nfl_player_id_1",
        "nfl_player_id_2",
        "contact",
    ]
    feature_cols = [c for c in df_val.columns if c not in meta_cols]

    # Calculate correlations
    correlations = {}
    for col in feature_cols:
        if pd.api.types.is_numeric_dtype(df_val[col]):
            # Handle potential NaNs just in case
            valid_mask = ~np.isnan(df_val[col]) & ~np.isnan(errors)
            if valid_mask.sum() > 0:
                corr = np.corrcoef(df_val.loc[valid_mask, col], errors[valid_mask])[
                    0, 1
                ]
                correlations[col] = corr
            else:
                correlations[col] = 0.0

    # Sort by absolute correlation
    sorted_corr = sorted(correlations.items(), key=lambda x: abs(x[1]), reverse=True)

    print("Top 10 Features associated with Error Magnitude:")
    for feature, corr in sorted_corr[:10]:
        print(f"{feature}: {corr:.4f}")


def main():
    # 1. Setup
    set_seed(SEED)
    print("Initializing Training Pipeline...")

    # Initialize pipeline
    # We use debug=False to run on the full dataset, but we will manually clamp
    # the estimators to ensure it fits within the 2-hour "Fast Baseline" requirement.
    pipeline = TrainingPipeline(debug=False)

    # Adjust configuration for speed
    # 3000 is too high for a fast baseline check. 800-1000 is sufficient for convergence
    # on this dataset size with early stopping.
    pipeline.model_config.lgbm_params["n_estimators"] = 1000
    pipeline.model_config.xgb_params["n_estimators"] = 1000
    pipeline.model_config.scout_n_estimators = 300  # Reduced from 500

    # 2. Execute Training
    # This runs: Scout -> Mining -> Expert -> Threshold Opt
    pipeline.run()

    # 3. Explicit Validation & Failure Analysis
    print("\nRunning Final Validation Assessment...")

    # Load validation data (using cache generated by pipeline)
    data_factory = DataFactory()
    df_val = data_factory.get_processed_dataset(mode="val", load_cached_data=True)

    # Prepare X_val
    meta_cols = [
        "contact_id",
        "game_play",
        "step",
        "nfl_player_id_1",
        "nfl_player_id_2",
        "contact",
    ]
    feature_cols = [c for c in df_val.columns if c not in meta_cols]
    X_val = df_val[feature_cols]
    y_val = df_val["contact"].values

    # Load Ensemble
    lgbm_path = "expert_lgbm.joblib"
    xgb_path = "expert_xgb.joblib"

    # Ensure models exist
    if not os.path.exists(os.path.join(MODEL_OUTPUT_DIR, lgbm_path)):
        print("Error: Expert LGBM model not found.")
        return

    predictor = EnsemblePredictor(lgbm_path=lgbm_path, xgb_path=xgb_path)

    # Predict probabilities
    val_probs = predictor.predict(X_val)

    # Load optimized threshold
    thresh_path = os.path.join(MODEL_OUTPUT_DIR, "best_threshold.npy")
    if os.path.exists(thresh_path):
        threshold = float(np.load(thresh_path)[0])
    else:
        threshold = 0.5

    # Binarize
    val_preds = (val_probs > threshold).astype(int)

    # Compute Metric
    final_mcc = compute_mcc(y_val, val_preds)

    # REQUIRED OUTPUT FORMAT
    print(f"Final Validation Metric: {final_mcc:.16f}")

    # Failure Analysis
    run_failure_analysis(df_val, val_probs)

    # 4. Conditional Inference
    TARGET_METRIC = 0.6782
    if final_mcc > TARGET_METRIC:
        print(
            f"\nValidation Metric ({final_mcc:.4f}) meets threshold ({TARGET_METRIC}). Generating submission..."
        )
        inference_pipeline = InferencePipeline()
        inference_pipeline.generate_submission(load_cached_data=True)
    else:
        print(
            f"\nValidation Metric ({final_mcc:.4f}) is below threshold ({TARGET_METRIC}). Skipping submission."
        )


if __name__ == "__main__":
    main()
