import os
import sys
import gc
import numpy as np
import pandas as pd
from sklearn.metrics import matthews_corrcoef

# Import from provided libraries
from library.config import Config
from library.training_pipeline import TrainingPipeline
from library.feature_engine import FeatureEngine
from library.model_zoo import EnsemblePredictor
from library.utils import load_npy, setup_logger, load_parquet


def set_seed(seed=42):
    np.random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)


def main():
    # 1. Setup
    set_seed(Config.SEED)
    logger = setup_logger(name="runfile", log_file="runfile.log")

    # Define sample size for fast baseline execution
    # 150k samples is enough for a strong signal but fast enough for <2h
    SAMPLE_SIZE = 150000

    logger.info("Initializing Training Pipeline...")
    pipeline = TrainingPipeline()

    # 2. Execute Training Pipeline
    # This handles Feature Gen -> Scout Training -> Mining -> Expert Training -> Threshold Opt
    pipeline.run(load_cached_data=True, sample_size=SAMPLE_SIZE)

    # 3. Validation and Failure Analysis
    logger.info("Starting Validation Analysis...")

    # Load validation features (generated by pipeline)
    # The pipeline saves them as features_val_sample_{SAMPLE_SIZE}.parquet or features_val.parquet
    # We check the likely filename based on FeatureEngine logic
    val_feature_file = (
        f"features_val_sample_{SAMPLE_SIZE}.parquet"
        if SAMPLE_SIZE
        else "features_val.parquet"
    )
    df_val = load_parquet(val_feature_file)

    if df_val is None:
        # Fallback if sample size wasn't used in filename or file missing
        df_val = load_parquet("features_val.parquet")

    if df_val is None:
        logger.error("Could not load validation features. Exiting.")
        sys.exit(1)

    # Identify feature columns
    exclude_cols = [
        "contact_id",
        "game_play",
        "step",
        "nfl_player_id_1",
        "nfl_player_id_2",
        "contact",
        "datetime",
        "step_offset",
    ]
    feature_cols = [c for c in df_val.columns if c not in exclude_cols]

    X_val = df_val[feature_cols]
    y_val = df_val["contact"].values

    # Load Models
    predictor = EnsemblePredictor()
    try:
        predictor.load_models("models/expert_lgbm.joblib", "models/expert_xgb.joblib")
    except FileNotFoundError as e:
        logger.error(f"Models not found: {e}")
        sys.exit(1)

    # Predict
    logger.info("Generating validation predictions...")
    y_pred_proba = predictor.predict(X_val)

    # Load Best Threshold
    thresh_arr = load_npy("models/best_threshold.npy")
    best_threshold = thresh_arr[0] if thresh_arr is not None else 0.5

    # Compute Metrics
    y_pred_binary = (y_pred_proba >= best_threshold).astype(int)
    mcc = matthews_corrcoef(y_val, y_pred_binary)

    # PRINT REQUIRED METRIC
    print(f"Final Validation Metric: {mcc}")

    # Failure Analysis
    logger.info("Performing Failure Analysis...")
    errors = np.abs(y_val - y_pred_proba)

    # Compute correlation between error and features
    # We use a subset of features to save time if many features exist
    analysis_df = X_val.copy()
    analysis_df["error"] = errors

    correlations = analysis_df.corr()["error"].drop("error")
    top_corr = correlations.abs().sort_values(ascending=False).head(5)

    print("\n--- Failure Analysis: Top Feature Correlations with Error ---")
    print(top_corr)
    print("-------------------------------------------------------------")

    # Cleanup memory
    del df_val, X_val, analysis_df
    gc.collect()

    # 4. Submission
    THRESHOLD_SCORE = 0.6865

    if mcc > THRESHOLD_SCORE:
        logger.info(
            f"Validation MCC ({mcc}) > {THRESHOLD_SCORE}. Generating submission..."
        )

        # Generate Test Features
        # Note: We do not sample test data, we need full inference
        df_test = FeatureEngine.generate_features(split="test", load_cached_data=True)

        if df_test is None or df_test.empty:
            logger.error("Test features are empty. Cannot generate submission.")
            return

        # Prepare Test Data
        # Ensure same columns
        X_test = df_test[feature_cols]

        # Predict
        test_probs = predictor.predict(X_test)
        test_preds = (test_probs >= best_threshold).astype(int)

        # Create Submission DataFrame
        submission = pd.DataFrame(
            {"contact_id": df_test["contact_id"], "contact": test_preds}
        )

        # Save
        sub_path = Config.SUBMISSION_PATH
        os.makedirs(os.path.dirname(sub_path), exist_ok=True)
        submission.to_csv(sub_path, index=False)

        logger.info(f"Submission saved to {sub_path} with {len(submission)} rows.")

    else:
        logger.warning(
            f"Validation MCC ({mcc}) <= {THRESHOLD_SCORE}. Skipping submission generation."
        )


if __name__ == "__main__":
    main()
