import os
import torch
import numpy as np
import pandas as pd
from scipy.stats import pearsonr

from library.config import Config
from library.utils import seed_everything, rmsle
from library.data import get_train_val_loaders, get_test_loader
from library.engine import fit


def main():
    # 1. Setup
    seed_everything(Config.SEED)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # 2. Train Model
    # Using 50 epochs for a fast baseline as requested
    print("Training model...")
    model = fit(load_cached_data=True, epochs=50)
    model.eval()

    # 3. Validation Assessment
    print("Performing validation...")
    # Load validation data (will use cache generated by fit)
    _, val_loader = get_train_val_loaders(
        load_cached_data=True, batch_size=Config.BATCH_SIZE
    )

    val_preds = []
    val_targets = []
    val_global_feats = []

    with torch.no_grad():
        for batch in val_loader:
            atomic_feats = batch["atomic_feats"].to(device)
            batch_indices = batch["batch_indices"].to(device)
            global_feats = batch["global_feats"].to(device)
            targets = batch["targets"].to(device)

            # Forward pass
            outputs = model(atomic_feats, batch_indices, global_feats)

            # Inverse transform: log(1+y) -> exp(x) - 1
            # Clip to prevent numerical instability
            outputs = torch.clamp(outputs, min=-20, max=20)
            preds_linear = torch.expm1(outputs)

            val_preds.append(preds_linear.cpu().numpy())
            val_targets.append(targets.cpu().numpy())
            val_global_feats.append(global_feats.cpu().numpy())

    val_preds = np.vstack(val_preds)
    val_targets = np.vstack(val_targets)
    val_global_feats = np.vstack(val_global_feats)

    # Compute Metric
    final_metric = rmsle(val_targets, val_preds)
    print(f"Final Validation Metric: {final_metric}")

    # 4. Failure Analysis
    print("\nFailure Analysis (Correlation with Error):")
    # Calculate absolute errors
    errors = np.abs(val_targets - val_preds)
    # errors shape: (N, 2) -> [formation_energy_error, bandgap_energy_error]

    # Global feature names based on compute_global_features in features.py
    # [lengths(3), angles(3), volume(1), density(1), n_atoms(1), fractions(3)]
    feat_names = [
        "lat_len_a",
        "lat_len_b",
        "lat_len_c",
        "lat_ang_alpha",
        "lat_ang_beta",
        "lat_ang_gamma",
        "vol",
        "density",
        "n_atoms",
        "frac_Al",
        "frac_Ga",
        "frac_In",
    ]

    target_names = ["formation_energy", "bandgap_energy"]

    for i, target_name in enumerate(target_names):
        print(f"  Target: {target_name}")
        target_errors = errors[:, i]

        correlations = []
        for j, feat_name in enumerate(feat_names):
            # Check for constant columns to avoid warnings
            if np.std(val_global_feats[:, j]) > 1e-9:
                corr, _ = pearsonr(val_global_feats[:, j], target_errors)
                correlations.append((feat_name, corr))
            else:
                correlations.append((feat_name, 0.0))

        # Sort by absolute correlation
        correlations.sort(key=lambda x: abs(x[1]), reverse=True)

        for feat, corr in correlations[:3]:
            print(f"    {feat}: {corr:.4f}")

    # 5. Submission
    THRESHOLD = 0.05479004207787702
    if final_metric < THRESHOLD:
        print("\nValidation metric meets threshold. Generating submission...")

        test_loader = get_test_loader(
            load_cached_data=True, batch_size=Config.BATCH_SIZE
        )

        test_preds = []
        test_ids = []

        with torch.no_grad():
            for batch in test_loader:
                atomic_feats = batch["atomic_feats"].to(device)
                batch_indices = batch["batch_indices"].to(device)
                global_feats = batch["global_feats"].to(device)
                batch_ids = batch["ids"]

                outputs = model(atomic_feats, batch_indices, global_feats)
                outputs = torch.clamp(outputs, min=-20, max=20)
                preds_linear = torch.expm1(outputs)

                test_preds.append(preds_linear.cpu().numpy())
                test_ids.append(batch_ids.numpy())

        test_preds = np.vstack(test_preds)
        test_ids = np.concatenate(test_ids)

        # Create DataFrame
        submission_df = pd.DataFrame(
            {
                "id": test_ids,
                "formation_energy_ev_natom": test_preds[:, 0],
                "bandgap_energy_ev": test_preds[:, 1],
            }
        )

        # Sort by ID just in case
        submission_df = submission_df.sort_values("id")

        # Save
        os.makedirs(os.path.dirname(Config.SUBMISSION_PATH), exist_ok=True)
        submission_df.to_csv(Config.SUBMISSION_PATH, index=False)
        print(f"Submission saved to {Config.SUBMISSION_PATH}")

    else:
        print(
            f"\nValidation metric {final_metric} is not lower than threshold {THRESHOLD}. Skipping submission."
        )


if __name__ == "__main__":
    main()
