import os
import sys
import torch
import torch.nn as nn
import torch.optim as optim
import pandas as pd
import numpy as np
import warnings

# Import from provided library files
from library.config import Config, seed_everything
from library.data import get_dataloaders
from library.model import SiameseDualAxisNet
from library.train import train_one_epoch, validate_one_epoch, CombinedLoss
from library.utils import score_function

# Suppress warnings for cleaner output
warnings.filterwarnings("ignore")


def main():
    # 1. Setup
    seed_everything(Config.SEED)
    device = Config.DEVICE

    # 2. Load Data
    # We use the metadata CSVs generated by the metadata script
    train_df = pd.read_csv(Config.TRAIN_CSV)
    val_df = pd.read_csv(Config.VAL_CSV)
    test_df = pd.read_csv(Config.TEST_CSV)

    # Initialize DataLoaders
    # We use the provided get_dataloaders function which handles transforms and batching
    train_loader, val_loader, test_loader = get_dataloaders(
        train_df, val_df, test_df, batch_size=Config.BATCH_SIZE
    )

    # 3. Model Initialization
    model = SiameseDualAxisNet().to(device)

    optimizer = optim.AdamW(
        model.parameters(), lr=Config.LR, weight_decay=Config.WEIGHT_DECAY
    )

    scheduler = optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=Config.T_MAX, eta_min=Config.MIN_LR
    )

    criterion = CombinedLoss().to(device)

    # 4. Training Loop
    best_score = -float("inf")
    patience_counter = 0
    best_model_path = Config.MODEL_SAVE_PATH

    # Ensure working directory exists
    os.makedirs(os.path.dirname(best_model_path), exist_ok=True)

    for epoch in range(Config.EPOCHS):
        # Train one epoch
        train_loss, train_m_loss, train_a_loss = train_one_epoch(
            model, train_loader, optimizer, criterion, device
        )

        # Validate one epoch
        val_score = validate_one_epoch(model, val_loader, device)

        # Update Scheduler
        scheduler.step()

        # Save best model
        if val_score > best_score:
            best_score = val_score
            torch.save(model.state_dict(), best_model_path)
            patience_counter = 0
        else:
            patience_counter += 1

        # Early Stopping
        if patience_counter >= Config.PATIENCE:
            break

    # 5. Final Validation Metric
    # Print exactly as required
    print(f"Final Validation Metric: {best_score}")

    # 6. Failure Analysis
    # Load best model for analysis
    model.load_state_dict(torch.load(best_model_path, map_location=device))
    model.eval()

    val_errors = []
    val_features = []

    with torch.no_grad():
        for inputs, targets in val_loader:
            axial_img, coronal_img, tabular = inputs
            axial_img = axial_img.to(device)
            coronal_img = coronal_img.to(device)
            tabular = tabular.to(device)

            # Targets
            base_fvc = targets["base_fvc"].to(device)
            week_delta = targets["week_delta"].to(device)
            true_fvc = targets["fvc"].cpu().numpy()

            # Forward
            outputs = model(axial_img, coronal_img, tabular)

            alpha = outputs["alpha"]

            # Predict FVC
            fvc_pred = (base_fvc + alpha * week_delta).cpu().numpy()

            # Calculate Absolute Error
            abs_error = np.abs(true_fvc - fvc_pred)
            val_errors.extend(abs_error)

            # Collect features for correlation analysis
            # Tabular tensor structure: [age, base_pct_norm, sex, smoke]
            # We also want Week Delta (time)
            batch_feats = tabular.cpu().numpy()
            batch_delta = week_delta.cpu().numpy().reshape(-1, 1)

            # Combine: Age, Percent, Sex, Smoke, Delta
            combined = np.hstack([batch_feats, batch_delta])
            val_features.extend(combined)

    # Create DataFrame for analysis
    val_features = np.array(val_features)
    analysis_df = pd.DataFrame(
        val_features,
        columns=["Age", "Baseline_Percent", "Sex", "SmokingStatus", "Week_Delta"],
    )
    analysis_df["Error_Magnitude"] = val_errors

    # Calculate correlations
    correlations = analysis_df.corr()["Error_Magnitude"].drop("Error_Magnitude")

    print("\nFailure Analysis (Correlation with Error Magnitude):")
    print(correlations)

    # 7. Submission Generation
    # Threshold check
    threshold = -6.569469928741455

    if best_score > threshold:
        submission_rows = []

        with torch.no_grad():
            for inputs, meta in test_loader:
                axial_img, coronal_img, tabular = inputs
                axial_img = axial_img.to(device)
                coronal_img = coronal_img.to(device)
                tabular = tabular.to(device)

                base_fvc = meta["base_fvc"].to(device)
                week_delta = meta["week_delta"].to(device)
                patient_weeks = meta["patient_week"]

                # Forward
                outputs = model(axial_img, coronal_img, tabular)

                alpha = outputs["alpha"]
                sigma_base = outputs["sigma_base"]
                sigma_growth = outputs["sigma_growth"]

                # Calculate Predictions
                fvc_pred = base_fvc + alpha * week_delta
                confidence = sigma_base + sigma_growth * torch.abs(week_delta)

                # Move to CPU
                fvc_pred = fvc_pred.cpu().numpy()
                confidence = confidence.cpu().numpy()

                # Clip confidence as per metric requirement (min 70)
                # Although metric function does it, we should output reasonable values
                confidence = np.maximum(confidence, 70)

                for pw, fvc, conf in zip(patient_weeks, fvc_pred, confidence):
                    submission_rows.append(
                        {"Patient_Week": pw, "FVC": fvc, "Confidence": conf}
                    )

        # Create Submission DataFrame
        sub_df = pd.DataFrame(submission_rows)

        # Ensure output directory exists
        os.makedirs(Config.SUBMISSION_DIR, exist_ok=True)

        # Save
        sub_df.to_csv(Config.SUBMISSION_PATH, index=False)


if __name__ == "__main__":
    main()
