import pandas as pd
import numpy as np
import os
import warnings
from sklearn.metrics import roc_auc_score

from library.config import Config
from library.utils import set_seed
from library.features import FeatureEngineer
from library.model_rf import RFPredictor
from library.model_mlp import MLPTrainer

# Suppress warnings for cleaner output
warnings.filterwarnings("ignore")


def run():
    # 1. Setup
    print("Initializing Hybrid Ensemble Pipeline...")
    set_seed(Config.RANDOM_STATE)

    # 2. Data Processing & Feature Engineering
    fe = FeatureEngineer()

    # Stream A: Random Forest Data (Tabular + TF-IDF + Alignment Scalar)
    print("\n--- Processing Stream A (Random Forest) ---")
    X_train_rf, X_val_rf, X_test_rf = fe.process_stream_a(load_cached_data=True)

    # Stream B: MLP Data (Embeddings + Sequences + Scaled Meta)
    print("\n--- Processing Stream B (Dual-Query MLP) ---")
    data_train_mlp, data_val_mlp, data_test_mlp = fe.process_stream_b(
        load_cached_data=True
    )

    # 3. Model Training

    # Train Random Forest
    print("\n--- Training Stream A: Random Forest ---")
    rf_model = RFPredictor()
    rf_model.train(X_train_rf)

    # Train MLP
    print("\n--- Training Stream B: Dual-Query MLP ---")
    mlp_trainer = MLPTrainer()
    # Note: MLPTrainer handles its own internal validation loop and checkpointing
    mlp_trainer.train(data_train_mlp, data_val_mlp)

    # 4. Evaluation & Ensemble
    print("\n--- Evaluating Ensemble on Validation Set ---")

    # Get predictions (Probabilities for Class 1)
    # RF handles dropping target internally if present
    rf_probs_val = rf_model.predict_proba(X_val_rf)

    # MLP predict_proba creates a test-mode dataset (ignoring y)
    mlp_probs_val = mlp_trainer.predict_proba(data_val_mlp)

    # Weighted Ensemble
    ensemble_probs_val = (Config.WEIGHT_RF * rf_probs_val) + (
        Config.WEIGHT_MLP * mlp_probs_val
    )

    # Calculate Metric
    # Extract target from X_val_rf
    y_val = X_val_rf["requester_received_pizza"].values
    val_auc = roc_auc_score(y_val, ensemble_probs_val)

    print(f"Final Validation Metric: {val_auc}")

    # 5. Failure Analysis
    print("\n--- Performing Failure Analysis ---")
    # Calculate absolute error
    errors = np.abs(y_val - ensemble_probs_val)

    # Correlate error with features in X_val_rf (excluding target)
    analysis_df = X_val_rf.drop(
        columns=["requester_received_pizza"], errors="ignore"
    ).copy()

    # Select only numeric columns for correlation
    numeric_df = analysis_df.select_dtypes(include=[np.number])

    # Compute correlations
    correlations = numeric_df.corrwith(pd.Series(errors, index=numeric_df.index))

    # Sort by absolute correlation
    sorted_corr = correlations.abs().sort_values(ascending=False)

    print("Top 10 Features Correlated with Prediction Error:")
    print(correlations.loc[sorted_corr.index[:10]])

    # 6. Submission
    threshold = 0.7036289345758168
    if val_auc > threshold:
        print(
            f"\nValidation AUC ({val_auc}) > Threshold ({threshold}). Generating submission..."
        )

        # Inference on Test Set
        rf_probs_test = rf_model.predict_proba(X_test_rf)
        mlp_probs_test = mlp_trainer.predict_proba(data_test_mlp)

        ensemble_probs_test = (Config.WEIGHT_RF * rf_probs_test) + (
            Config.WEIGHT_MLP * mlp_probs_test
        )

        # Load ID mapping from test.csv (generated by metadata script)
        df_test_meta = pd.read_csv(Config.TEST_PATH)

        # Create submission DataFrame
        submission = pd.DataFrame(
            {
                "request_id": df_test_meta["request_id"],
                "requester_received_pizza": ensemble_probs_test,
            }
        )

        # Load sample submission to ensure correct format and order
        sample_sub_path = "./input/sampleSubmission.csv"
        if os.path.exists(sample_sub_path):
            sample_sub = pd.read_csv(sample_sub_path)
            # Map predictions to sample submission IDs
            pred_map = dict(
                zip(submission["request_id"], submission["requester_received_pizza"])
            )
            sample_sub["requester_received_pizza"] = (
                sample_sub["request_id"].map(pred_map).fillna(0)
            )
            final_submission = sample_sub
        else:
            # Fallback if sample submission not found (unlikely)
            final_submission = submission

        # Save
        os.makedirs(Config.SUBMISSION_DIR, exist_ok=True)
        final_submission.to_csv(Config.SUBMISSION_FILE, index=False)
        print(f"Submission saved to {Config.SUBMISSION_FILE}")

    else:
        print(
            f"\nValidation AUC ({val_auc}) <= Threshold ({threshold}). Submission skipped."
        )


if __name__ == "__main__":
    run()
