import os
import pandas as pd
import torch
import torch.optim as optim
from torch.utils.data import DataLoader

# Import provided library modules
from library.config import Config
from library.dataset import CatheterDataset, get_transforms
from library.model import CatheterResNet
from library.engine import fit, predict, set_seed


def main():
    print("Initializing demonstration...")

    # -------------------------------------------------------------------------
    # 1. Configuration Adjustments for Demo
    # -------------------------------------------------------------------------
    # Enable Debug mode to use a small subset of data (100 samples)
    Config.DEBUG = True
    Config.DEBUG_SAMPLE_SIZE = 50  # Small sample for quick execution

    # Reduce training parameters for speed
    Config.EPOCHS = 1
    Config.BATCH_SIZE = 4
    Config.NUM_WORKERS = 2

    # Create necessary output directories
    Config.create_output_dirs()

    # Set seed for reproducibility
    set_seed(Config.SEED)

    print(f"Debug Mode: {Config.DEBUG}")
    print(f"Device: {Config.DEVICE}")

    # -------------------------------------------------------------------------
    # 2. Data Loading & Verification
    # -------------------------------------------------------------------------
    print("\nLoading metadata...")
    # Load metadata generated by the previous step
    df_train = pd.read_csv(Config.TRAIN_METADATA_PATH)
    df_val = pd.read_csv(Config.VAL_METADATA_PATH)
    df_test = pd.read_csv(Config.TEST_METADATA_PATH)

    print(f"Original Train size: {len(df_train)}")
    print(f"Original Val size: {len(df_val)}")
    print(f"Original Test size: {len(df_test)}")

    # Initialize Datasets
    # Note: Config.DEBUG=True inside the class will subsample these dataframes automatically
    train_dataset = CatheterDataset(
        df_train, transforms=get_transforms("train"), mode="train"
    )
    val_dataset = CatheterDataset(df_val, transforms=get_transforms("val"), mode="val")
    test_dataset = CatheterDataset(
        df_test, transforms=get_transforms("test"), mode="test"
    )

    print(f"Debug Train size: {len(train_dataset)}")

    # Initialize DataLoaders
    train_loader = DataLoader(
        train_dataset,
        batch_size=Config.BATCH_SIZE,
        shuffle=True,
        num_workers=Config.NUM_WORKERS,
        pin_memory=True,
    )

    val_loader = DataLoader(
        val_dataset,
        batch_size=Config.BATCH_SIZE,
        shuffle=False,
        num_workers=Config.NUM_WORKERS,
        pin_memory=True,
    )

    test_loader = DataLoader(
        test_dataset,
        batch_size=Config.BATCH_SIZE,
        shuffle=False,
        num_workers=Config.NUM_WORKERS,
        pin_memory=True,
    )

    # VERIFICATION: Check Batch Shapes
    print("Verifying data shapes...")
    sample_imgs, sample_labels = next(iter(train_loader))

    # Expected: (Batch, 3, 512, 512)
    expected_img_shape = (Config.BATCH_SIZE, 3, Config.IMAGE_SIZE, Config.IMAGE_SIZE)
    # Expected: (Batch, 11)
    expected_label_shape = (Config.BATCH_SIZE, Config.NUM_CLASSES)

    assert (
        sample_imgs.shape == expected_img_shape
    ), f"Image shape mismatch. Expected {expected_img_shape}, got {sample_imgs.shape}"
    assert (
        sample_labels.shape == expected_label_shape
    ), f"Label shape mismatch. Expected {expected_label_shape}, got {sample_labels.shape}"

    print("Data shapes verified successfully.")

    # -------------------------------------------------------------------------
    # 3. Model Initialization & Verification
    # -------------------------------------------------------------------------
    print("\nInitializing model...")
    model = CatheterResNet(pretrained=True, num_classes=Config.NUM_CLASSES)
    model.to(Config.DEVICE)

    # VERIFICATION: Forward Pass
    print("Verifying model forward pass...")
    with torch.no_grad():
        dummy_input = sample_imgs.to(Config.DEVICE)
        dummy_output = model(dummy_input)

    assert (
        dummy_output.shape == expected_label_shape
    ), f"Model output shape mismatch. Expected {expected_label_shape}, got {dummy_output.shape}"

    print("Model forward pass verified successfully.")

    # -------------------------------------------------------------------------
    # 4. Training Simulation
    # -------------------------------------------------------------------------
    print("\nStarting training loop (1 epoch)...")

    optimizer = optim.AdamW(
        model.parameters(), lr=Config.LEARNING_RATE, weight_decay=Config.WEIGHT_DECAY
    )
    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=Config.EPOCHS)

    fit(
        model=model,
        train_loader=train_loader,
        val_loader=val_loader,
        optimizer=optimizer,
        scheduler=scheduler,
        device=Config.DEVICE,
        epochs=Config.EPOCHS,
        patience=Config.PATIENCE,
        save_path=Config.CHECKPOINT_PATH,
    )

    # VERIFICATION: Checkpoint creation
    assert os.path.exists(
        Config.CHECKPOINT_PATH
    ), f"Model checkpoint not found at {Config.CHECKPOINT_PATH}"
    print(f"Training complete. Checkpoint saved at {Config.CHECKPOINT_PATH}")

    # -------------------------------------------------------------------------
    # 5. Inference & Submission
    # -------------------------------------------------------------------------
    print("\nStarting inference...")

    # Load best model weights
    model.load_state_dict(
        torch.load(Config.CHECKPOINT_PATH, map_location=Config.DEVICE)
    )

    # Pass the *original* test dataframe (or the one used to create the dataset) to predict
    # The dataset might be a subset due to DEBUG, so we ensure alignment.
    # In this demo, test_dataset.df is the subset used.
    predict(
        model=model,
        dataloader=test_loader,
        df_test=test_dataset.df,
        device=Config.DEVICE,
        output_path=Config.SUBMISSION_PATH,
    )

    # VERIFICATION: Submission File
    assert os.path.exists(
        Config.SUBMISSION_PATH
    ), f"Submission file not found at {Config.SUBMISSION_PATH}"

    sub_df = pd.read_csv(Config.SUBMISSION_PATH)

    # Check rows (should match the debug sample size or full size depending on logic)
    # Since we set DEBUG=True, test_dataset is subsampled.
    expected_rows = len(test_dataset)
    assert (
        len(sub_df) == expected_rows
    ), f"Submission row count mismatch. Expected {expected_rows}, got {len(sub_df)}"

    # Check columns: StudyInstanceUID + 11 Targets
    expected_cols = ["StudyInstanceUID"] + Config.TARGET_COLS
    assert (
        list(sub_df.columns) == expected_cols
    ), f"Submission columns mismatch.\nExpected: {expected_cols}\nGot: {list(sub_df.columns)}"

    print(f"Inference complete. Submission verified. Shape: {sub_df.shape}")
    print("\nDemonstration finished successfully.")


if __name__ == "__main__":
    main()
