import os
import gc
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import StratifiedKFold
from torch.utils.data import DataLoader
from transformers import (
    AutoTokenizer,
    DataCollatorWithPadding,
    get_cosine_schedule_with_warmup,
)
from torch.optim import AdamW

# Import provided library modules
import importlib
import library.config
import library.models
import library.engine
import library.dataset
import library.lexical_model
import library.utils

# Cite debug_lesson_3: Restart Interpreter / Reload Modules
# Force reload of library modules to ensure updates to Config, Models, and Engine are picked up
importlib.reload(library.config)
importlib.reload(library.utils)
importlib.reload(library.dataset)
importlib.reload(library.models)
importlib.reload(library.engine)
importlib.reload(library.lexical_model)

from library.config import Config
from library.utils import (
    seed_everything,
    compute_qwk,
    optimize_thresholds,
    apply_thresholds,
)
from library.dataset import load_data, EssayDataset
from library.models import EssayDebertaModel
from library.lexical_model import LexicalRidgePipeline
from library.engine import run_training, eval_fn


def main():
    # --- 1. Setup & Configuration ---
    seed_everything(Config.seed)

    # Override Config for fast baseline execution
    Config.epochs = 1

    # Ensure output directories exist
    os.makedirs(Config.output_dir, exist_ok=True)
    os.makedirs(os.path.dirname(Config.submission_path), exist_ok=True)

    print("Loading Data...")
    # Load Data
    # df_train_cv: Used for 5-Fold Cross-Validation to train models and learn ensemble parameters
    df_train_cv = load_data("train", load_cached_data=True)
    # df_holdout: Strictly held-out set for final validation metric
    df_holdout = load_data("val", load_cached_data=True)
    # df_test: Target for submission
    df_test = load_data("test", load_cached_data=True)

    # Initialize Tokenizer & Collator
    tokenizer = AutoTokenizer.from_pretrained(Config.model_name)
    data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

    # Prepare Cross-Validation
    skf = StratifiedKFold(n_splits=Config.folds, shuffle=True, random_state=Config.seed)

    # Initialize Arrays for Predictions
    # OOF: Out-Of-Fold predictions for the training set
    oof_preds_semantic = np.zeros(len(df_train_cv))
    oof_preds_lexical = np.zeros(len(df_train_cv))

    # Holdout: Accumulate predictions from each fold
    holdout_preds_semantic = np.zeros(len(df_holdout))
    holdout_preds_lexical = np.zeros(len(df_holdout))

    # Test: Accumulate predictions from each fold
    test_preds_semantic = np.zeros(len(df_test))
    test_preds_lexical = np.zeros(len(df_test))

    print(f"Starting {Config.folds}-Fold Cross-Validation...")

    for fold, (train_idx, val_idx) in enumerate(
        skf.split(df_train_cv, df_train_cv["score"])
    ):
        print(f"\n=== Fold {fold + 1}/{Config.folds} ===")

        # Create Fold DataFrames
        fold_train_df = df_train_cv.iloc[train_idx].reset_index(drop=True)
        fold_val_df = df_train_cv.iloc[val_idx].reset_index(drop=True)

        # ---------------------------
        # A. Lexical Branch (Ridge)
        # ---------------------------
        print("Training Lexical Model...")
        lexical_pipeline = LexicalRidgePipeline()
        # run_fold trains on fold_train, predicts on fold_val (OOF) and df_test
        lex_results = lexical_pipeline.run_fold(fold_train_df, fold_val_df, df_test)

        # Store OOF predictions
        oof_preds_lexical[val_idx] = lex_results["val_preds"]

        # Predict on Holdout (Manual transform needed)
        vec = lex_results["vectorizer"]
        model_ridge = lex_results["model"]
        X_holdout = vec.transform(df_holdout["full_text"])
        p_holdout_lex = model_ridge.predict(X_holdout)
        # Clip and accumulate
        holdout_preds_lexical += np.clip(p_holdout_lex, 1, 6) / Config.folds

        # Accumulate Test predictions (already generated by pipeline)
        test_preds_lexical += lex_results["test_preds"] / Config.folds

        # ---------------------------
        # B. Semantic Branch (DeBERTa)
        # ---------------------------
        print("Training Semantic Model...")

        # Create Datasets
        train_dataset = EssayDataset(
            fold_train_df, tokenizer, Config.max_length, is_test=False
        )
        val_dataset = EssayDataset(
            fold_val_df, tokenizer, Config.max_length, is_test=False
        )
        holdout_dataset = EssayDataset(
            df_holdout, tokenizer, Config.max_length, is_test=False
        )
        test_dataset = EssayDataset(df_test, tokenizer, Config.max_length, is_test=True)

        # Create DataLoaders
        train_loader = DataLoader(
            train_dataset,
            batch_size=Config.train_batch_size,
            shuffle=True,
            num_workers=Config.num_workers,
            collate_fn=data_collator,
            pin_memory=True,
            drop_last=True,
        )
        val_loader = DataLoader(
            val_dataset,
            batch_size=Config.valid_batch_size,
            shuffle=False,
            num_workers=Config.num_workers,
            collate_fn=data_collator,
            pin_memory=True,
        )
        holdout_loader = DataLoader(
            holdout_dataset,
            batch_size=Config.valid_batch_size,
            shuffle=False,
            num_workers=Config.num_workers,
            collate_fn=data_collator,
            pin_memory=True,
        )
        test_loader = DataLoader(
            test_dataset,
            batch_size=Config.valid_batch_size,
            shuffle=False,
            num_workers=Config.num_workers,
            collate_fn=data_collator,
            pin_memory=True,
        )

        # Initialize Model, Optimizer, Scheduler
        device = Config.device
        model_semantic = EssayDebertaModel(pretrained=True)
        model_semantic.to(device)

        optimizer = AdamW(
            model_semantic.parameters(),
            lr=Config.learning_rate,
            weight_decay=Config.weight_decay,
        )
        num_training_steps = len(train_loader) * Config.epochs
        scheduler = get_cosine_schedule_with_warmup(
            optimizer,
            num_warmup_steps=int(num_training_steps * Config.warmup_ratio),
            num_training_steps=num_training_steps,
        )

        # Train Loop
        save_path = os.path.join(Config.model_dir, f"deberta_fold_{fold}.bin")
        run_training(
            model_semantic,
            train_loader,
            val_loader,
            optimizer,
            device,
            scheduler,
            epochs=Config.epochs,
            patience=Config.early_stopping_patience,
            save_path=save_path,
        )

        # Inference
        print("Generating Semantic Predictions...")

        # OOF (Validation for this fold)
        _, _, p_val_sem = eval_fn(model_semantic, val_loader, device)
        oof_preds_semantic[val_idx] = p_val_sem

        # Holdout
        _, _, p_holdout_sem = eval_fn(model_semantic, holdout_loader, device)
        holdout_preds_semantic += p_holdout_sem / Config.folds

        # Test
        _, _, p_test_sem = eval_fn(model_semantic, test_loader, device)
        test_preds_semantic += p_test_sem / Config.folds

        # Cleanup
        del (
            model_semantic,
            optimizer,
            scheduler,
            train_loader,
            val_loader,
            holdout_loader,
            test_loader,
        )
        torch.cuda.empty_cache()
        gc.collect()

    # --- 2. Ensemble Optimization ---
    print("\n=== Ensemble Optimization ===")

    y_true_cv = df_train_cv["score"].values

    # Find optimal alpha for: alpha * semantic + (1-alpha) * lexical
    best_alpha = 0.5
    best_qwk = -1.0

    # Coarse search
    for alpha in np.linspace(0, 1, 101):
        combined_oof = alpha * oof_preds_semantic + (1 - alpha) * oof_preds_lexical
        # Use default thresholds for alpha search
        preds_int = apply_thresholds(combined_oof, [1.5, 2.5, 3.5, 4.5, 5.5])
        score = compute_qwk(y_true_cv, preds_int)
        if score > best_qwk:
            best_qwk = score
            best_alpha = alpha

    print(f"Best Alpha: {best_alpha:.2f} (CV QWK: {best_qwk:.4f})")

    # Combine OOF with best alpha
    final_oof_continuous = (
        best_alpha * oof_preds_semantic + (1 - best_alpha) * oof_preds_lexical
    )

    # Optimize Thresholds on OOF
    print("Optimizing Thresholds...")
    opt_thresholds = optimize_thresholds(y_true_cv, final_oof_continuous)
    print(f"Optimal Thresholds: {opt_thresholds}")

    # --- 3. Final Validation (Hold-out) ---
    print("\n=== Final Validation (Hold-out) ===")

    # Combine Holdout Predictions
    final_holdout_continuous = (
        best_alpha * holdout_preds_semantic + (1 - best_alpha) * holdout_preds_lexical
    )

    # Apply Thresholds
    final_holdout_int = apply_thresholds(final_holdout_continuous, opt_thresholds)

    # Compute Metric
    y_true_holdout = df_holdout["score"].values
    final_metric = compute_qwk(y_true_holdout, final_holdout_int)

    # REQUIRED PRINT
    print(f"Final Validation Metric: {final_metric}")

    # --- 4. Failure Analysis ---
    print("\n=== Failure Analysis ===")

    # Calculate absolute error
    errors = np.abs(y_true_holdout - final_holdout_int)

    # Compute Word Counts for Holdout (Feature for analysis)
    word_counts = df_holdout["full_text"].apply(lambda x: len(str(x).split())).values

    # Correlation
    corr = np.corrcoef(errors, word_counts)[0, 1]
    print(f"Correlation between Error and Word Count: {corr}")

    # --- 5. Submission ---
    THRESHOLD_SCORE = 0.8307992749024942

    if final_metric > THRESHOLD_SCORE:
        print("\nValidation metric met. Generating submission...")

        # Combine Test Predictions
        final_test_continuous = (
            best_alpha * test_preds_semantic + (1 - best_alpha) * test_preds_lexical
        )

        # Apply Thresholds
        final_test_int = apply_thresholds(final_test_continuous, opt_thresholds)

        # Create Submission DataFrame
        sub_df = pd.DataFrame(
            {"essay_id": df_test["essay_id"], "score": final_test_int}
        )

        # Save
        sub_df.to_csv(Config.submission_path, index=False)
        print(f"Submission saved to {Config.submission_path}")
    else:
        print(
            f"\nValidation metric {final_metric} did not meet threshold {THRESHOLD_SCORE}. Skipping submission."
        )


if __name__ == "__main__":
    main()
