import os
import time
import torch
import torch.nn as nn
import torch.optim as optim
import pandas as pd
import numpy as np

# Import from provided library modules
from library.model import CGCNN
from library.data_loader import get_train_val_test_loaders
from library.utils import AverageMeter, Normalizer, set_seed
from library.trainer import Trainer

# Hyperparameters
BATCH_SIZE = 64
EPOCHS = 80  # Cite solution_lesson_node_00003
LR = 1e-3  # Cite solution_lesson_node_00003
WEIGHT_DECAY = 1e-4  # Cite solution_lesson_node_00003
PATIENCE = 20
RADIUS = 6.0  # Cite solution_lesson_node_00003
NUM_WORKERS = 2
SEED = 42
METADATA_DIR = "./metadata"
CHECKPOINT_DIR = "./working/checkpoints"
SUBMISSION_DIR = "./submission"
BEST_MODEL_PATH = os.path.join(CHECKPOINT_DIR, "best_model.pth")
SUBMISSION_PATH = os.path.join(SUBMISSION_DIR, "submission.csv")


def main():
    # 1. Setup
    set_seed(SEED)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    os.makedirs(CHECKPOINT_DIR, exist_ok=True)
    os.makedirs(SUBMISSION_DIR, exist_ok=True)

    # 2. Data Loading
    print("Initializing DataLoaders...")
    # load_cached_data=True will try to use the cache generated by previous runs or generate it if missing
    train_loader, val_loader, test_loader = get_train_val_test_loaders(
        batch_size=BATCH_SIZE,
        radius=RADIUS,
        num_workers=NUM_WORKERS,
        load_cached_data=True,
    )

    # 3. Calculate Normalization Statistics
    print("Calculating normalizer statistics from training data...")
    all_targets = []
    # We iterate through the loader to gather all targets.
    # Since shuffle=True for train_loader, the order doesn't matter for stats.
    for _, _, _, _, targets, _ in train_loader:
        all_targets.append(targets)
    all_targets = torch.cat(all_targets, dim=0)

    normalizer = Normalizer(tensor=all_targets)
    # Move stats to device
    normalizer.mean = normalizer.mean.to(device)
    normalizer.std = normalizer.std.to(device)

    print(f"Normalizer Mean: {normalizer.mean.cpu().numpy()}")
    print(f"Normalizer Std:  {normalizer.std.cpu().numpy()}")

    # 4. Model Initialization
    # Atoms: O(8), Al(13), Ga(31), In(49) -> Mapped to 0, 1, 2, 3 in data_loader
    model = CGCNN(
        orig_atom_fea_len=4,
        atom_fea_len=64,
        n_conv=4,
        h_fea_len=128,
        n_h=2,
        n_targets=2,
        radius=RADIUS,
        n_rbf=50,
    ).to(device)

    optimizer = optim.Adam(model.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)
    criterion = nn.MSELoss()

    # Scheduler to reduce LR on plateau
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode="min", factor=0.5, patience=4
    )

    trainer = Trainer(model, optimizer, criterion, scheduler, device, normalizer)

    # 5. Training Loop
    print(f"Starting training for {EPOCHS} epochs...")
    best_val_loss = float("inf")
    patience_counter = 0

    for epoch in range(1, EPOCHS + 1):
        start_time = time.time()

        train_loss = trainer.train_epoch(train_loader, epoch)
        val_loss, val_rmsle = trainer.validate(val_loader)

        # Update scheduler
        scheduler.step(val_loss)

        elapsed = time.time() - start_time
        print(
            f"Epoch {epoch:03d}: Train Loss: {train_loss:.6f} | "
            f"Val Loss: {val_loss:.6f} | Val RMSLE: {val_rmsle:.6f} | "
            f"Time: {elapsed:.2f}s"
        )

        # Checkpointing and Early Stopping
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            patience_counter = 0
            torch.save(model.state_dict(), BEST_MODEL_PATH)
        else:
            patience_counter += 1
            if patience_counter >= PATIENCE:
                print(f"Early stopping triggered at epoch {epoch}.")
                break

    # 6. Final Validation Assessment
    print("Loading best model for final evaluation...")
    model.load_state_dict(torch.load(BEST_MODEL_PATH))
    model.eval()

    # Compute metric on full validation set
    _, final_val_rmsle = trainer.validate(val_loader)
    print(f"Final Validation Metric: {final_val_rmsle}")

    # 7. Failure Analysis
    print("Performing failure analysis...")
    # Load validation metadata
    val_meta_path = os.path.join(METADATA_DIR, "val_metadata.csv")
    val_df = pd.read_csv(val_meta_path)

    # Collect predictions and targets
    val_preds_list = []
    val_targets_list = []
    val_ids_list = []

    with torch.no_grad():
        for atom_fea, edge_index, edge_dist, batch_index, targets, ids in val_loader:
            atom_fea = atom_fea.to(device)
            edge_index = edge_index.to(device)
            edge_dist = edge_dist.to(device)
            batch_index = batch_index.to(device)

            # Predict
            preds_norm = model(atom_fea, edge_index, edge_dist, batch_index)
            preds = normalizer.denorm(preds_norm)

            val_preds_list.append(preds.cpu().numpy())
            val_targets_list.append(targets.numpy())
            val_ids_list.append(ids.numpy())

    val_preds = np.concatenate(val_preds_list, axis=0)
    val_targets = np.concatenate(val_targets_list, axis=0)
    val_ids = np.concatenate(val_ids_list, axis=0)

    # Calculate Mean Absolute Error per sample
    errors = np.abs(val_preds - val_targets)
    mean_errors = np.mean(errors, axis=1)

    # Create analysis dataframe
    analysis_df = pd.DataFrame({"id": val_ids, "mean_error": mean_errors})

    # Merge with features
    # Ensure 'id' types match
    val_df["id"] = val_df["id"].astype(int)
    analysis_df["id"] = analysis_df["id"].astype(int)
    merged_df = analysis_df.merge(val_df, on="id", how="left")

    # Define features to check correlation against
    feature_cols = [
        "number_of_total_atoms",
        "percent_atom_al",
        "percent_atom_ga",
        "percent_atom_in",
        "lattice_vector_1_ang",
        "lattice_vector_2_ang",
        "lattice_vector_3_ang",
        "lattice_angle_alpha_degree",
        "lattice_angle_beta_degree",
        "lattice_angle_gamma_degree",
    ]

    # Calculate correlations
    print("Correlation between Mean Error and Features:")
    correlations = (
        merged_df[feature_cols]
        .corrwith(merged_df["mean_error"])
        .sort_values(ascending=False)
    )
    print(correlations)

    # 8. Generate Submission
    if final_val_rmsle < 0.057427:
        print(f"Generating submission to {SUBMISSION_PATH}...")
        trainer.predict(test_loader, SUBMISSION_PATH)
        print("Submission generation complete.")
    else:
        print(
            f"Validation metric {final_val_rmsle} is not lower than 0.057427. Skipping submission."
        )


if __name__ == "__main__":
    main()
