import os
import shutil
import numpy as np
import torch
from scipy.stats import pearsonr

# Import from provided library files
from library.config import HYPERPARAMS, SEED, CHECKPOINT_DIR, SUBMISSION_DIR
from library.utils import (
    set_seed,
    compute_metric_score,
    levenshtein_distance,
    decode_sequence,
)
from library.data_loader import get_dataloaders
from library.trainer import Trainer


def main():
    # 1. Setup
    set_seed(SEED)
    print("Initializing RLSG-CN Pipeline...")

    # 2. Data Loading
    # The dataset is relatively small (~1700 samples). An A100 can handle this very quickly.
    # We use the full dataset to maximize performance but limit epochs for speed.
    print("Loading Data...")
    train_loader, val_loader, test_loader = get_dataloaders(
        batch_size=HYPERPARAMS["batch_size"], num_workers=2, sample_limit=None
    )

    # 3. Model Training
    print("Initializing Trainer...")
    trainer = Trainer(train_loader, val_loader, test_loader)

    # Run training for a limited number of epochs to ensure quick baseline execution
    # 15 epochs should be sufficient for the model to learn significant patterns
    # given the pre-trained nature or fast convergence of TCNs.
    print("Starting Training...")
    trainer.fit(num_epochs=15)

    # 4. Validation & Failure Analysis
    print("Running Validation Analysis...")

    # Load the best model weights saved during training
    best_model_path = os.path.join(CHECKPOINT_DIR, "best_model.pth")
    if os.path.exists(best_model_path):
        trainer.model.load_state_dict(
            torch.load(best_model_path, map_location=trainer.device)
        )

    trainer.model.eval()

    val_preds = []
    val_targets = []
    val_lengths = []
    val_target_counts = []

    # Iterate through validation set to collect detailed stats
    with torch.no_grad():
        for batch in val_loader:
            features = batch["features"].to(trainer.device)
            mask = batch["mask"].to(trainer.device)
            cls_target = batch["cls_target"].cpu().numpy()
            lengths = batch["lengths"].cpu().numpy()

            # Forward pass
            outputs = trainer.model(features, mask)

            # Use Stage 3 (final refinement) probabilities
            probs = outputs["stage3"]["cls_probs"].cpu().numpy()

            for i in range(len(lengths)):
                length = lengths[i]
                # Extract valid sequence
                p = probs[i, :length, :]

                # Post-process (Argmax -> Median Filter -> Decode)
                pred_seq = trainer._post_process_single(p)

                # Get Ground Truth Sequence
                t_frames = cls_target[i, :length]
                t_seq = decode_sequence(t_frames)

                val_preds.append(pred_seq)
                val_targets.append(t_seq)
                val_lengths.append(length)
                val_target_counts.append(len(t_seq))

    # Compute Final Metric
    final_metric = compute_metric_score(val_preds, val_targets)
    print(f"Final Validation Metric: {final_metric}")

    # Failure Analysis
    # Calculate Levenshtein distance for each sample
    errors = [levenshtein_distance(p, t) for p, t in zip(val_preds, val_targets)]

    if len(errors) > 1:
        # Correlation with Input Sequence Length (Frames)
        corr_len, _ = pearsonr(errors, val_lengths)
        # Correlation with Target Complexity (Number of Gestures)
        corr_count, _ = pearsonr(errors, val_target_counts)

        print("Failure Analysis Results:")
        print(f"Correlation (Error vs Sequence Length): {corr_len:.4f}")
        print(f"Correlation (Error vs Gesture Count): {corr_count:.4f}")
    else:
        print("Insufficient validation samples for failure analysis.")

    # 5. Submission
    # Threshold defined in task
    threshold = 0.06789606035205364

    if final_metric < threshold:
        print(f"Metric {final_metric} < {threshold}. Generating submission...")
        trainer.predict()

        # The trainer saves to working/idea_34/submission/submission.csv
        # We need to ensure it is also available at ./submission/submission.csv as per instructions
        generated_sub_path = os.path.join(SUBMISSION_DIR, "submission.csv")
        target_sub_dir = "./submission"
        target_sub_path = os.path.join(target_sub_dir, "submission.csv")

        if os.path.exists(generated_sub_path):
            os.makedirs(target_sub_dir, exist_ok=True)
            shutil.copy(generated_sub_path, target_sub_path)
            print(f"Submission file copied to {target_sub_path}")
        else:
            print("Error: Submission file was not generated by trainer.")
    else:
        print(f"Metric {final_metric} >= {threshold}. Submission generation skipped.")


if __name__ == "__main__":
    main()
