import os
import sys
import numpy as np
import pandas as pd
import torch
import soundfile as sf
from scipy.stats import pearsonr
from torch.utils.data import DataLoader

# Import from provided library
from library.config import Config
from library.utils import seed_everything, calculate_auc
from library.dataset import get_datasets, WhaleClassifier
from library.train import train_model, inference


def perform_failure_analysis(val_df, val_data, val_labels, val_preds):
    """
    Analyzes the correlation between model error and input features.
    """
    print("\n=== Failure Analysis ===")

    # Calculate Error Magnitude
    errors = np.abs(val_labels - val_preds)

    # Feature 1: Audio Duration (from file)
    durations = []
    print("Extracting audio metadata for failure analysis...")
    for idx, row in val_df.iterrows():
        full_path = os.path.join(Config.INPUT_ROOT, row["file_path"])
        try:
            info = sf.info(full_path)
            durations.append(info.duration)
        except:
            durations.append(0.0)
    durations = np.array(durations)

    # Feature 2 & 3: Spectrogram Statistics (Mean intensity, Contrast/Std)
    # val_data is (N, 224, 224)
    spec_means = np.mean(val_data, axis=(1, 2))
    spec_stds = np.std(val_data, axis=(1, 2))

    # Calculate Correlations
    features = {
        "Audio Duration": durations,
        "Spectrogram Mean (Signal Strength)": spec_means,
        "Spectrogram Std (Contrast)": spec_stds,
    }

    print(f"{'Feature':<40} | {'Correlation with Error':<25}")
    print("-" * 65)
    for name, feature_values in features.items():
        if len(feature_values) != len(errors):
            print(f"Skipping {name} due to length mismatch.")
            continue

        # Handle potential NaNs or constants
        if np.std(feature_values) == 0:
            corr = 0.0
        else:
            corr, _ = pearsonr(feature_values, errors)

        print(f"{name:<40} | {corr:.6f}")
    print("-" * 65)


def main():
    # 1. Setup
    seed_everything(Config.SEED)
    device = torch.device(Config.DEVICE)
    print(f"Using device: {device}")

    # Threshold for submission
    TARGET_THRESHOLD = 0.9959177895986835

    # 2. Load Data
    print("Loading datasets...")
    # load_cached_data=True will use the .npy files generated by dataset.py
    train_dataset, val_dataset, test_dataset = get_datasets(load_cached_data=True)

    # Load Validation Metadata for file paths (needed for failure analysis)
    val_df = pd.read_csv(Config.VAL_CSV)

    # Prepare DataLoaders for Inference
    val_loader = DataLoader(
        val_dataset,
        batch_size=Config.BATCH_SIZE,
        shuffle=False,
        num_workers=Config.NUM_WORKERS,
        pin_memory=True,
    )

    test_loader = DataLoader(
        test_dataset,
        batch_size=Config.BATCH_SIZE,
        shuffle=False,
        num_workers=Config.NUM_WORKERS,
        pin_memory=True,
    )

    # 3. Train Ensemble
    ensemble_val_preds = []
    ensemble_test_preds = []

    for arch in Config.MODEL_ARCHS:
        # A. Train
        best_model_path = train_model(arch, train_dataset, val_dataset, device)

        # B. Load Best Model for Inference
        print(f"Loading best weights for {arch} from {best_model_path}...")
        model = WhaleClassifier(model_name=arch, pretrained=False)
        model.load_state_dict(torch.load(best_model_path, map_location=device))
        model = model.to(device)
        model.eval()

        # C. Inference on Validation Set
        print(f"Validating {arch}...")
        val_preds = inference(model, val_loader, device)
        ensemble_val_preds.append(val_preds)

        # D. Inference on Test Set
        print(f"Inferencing {arch} on Test Set...")
        test_preds = inference(model, test_loader, device)
        ensemble_test_preds.append(test_preds)

        # Cleanup to save memory
        del model
        torch.cuda.empty_cache()

    # 4. Ensemble Aggregation (Soft Voting)
    print("\nComputing Ensemble Metrics...")
    avg_val_preds = np.mean(ensemble_val_preds, axis=0)

    # 5. Calculate Final Metric
    val_labels = val_dataset.labels
    final_auc = calculate_auc(val_labels, avg_val_preds)

    # REQUIRED OUTPUT
    print(f"Final Validation Metric: {final_auc}")

    # 6. Failure Analysis
    # We use the raw data from the dataset object for feature extraction
    perform_failure_analysis(val_df, val_dataset.data, val_labels, avg_val_preds)

    # 7. Submission Logic
    if final_auc > TARGET_THRESHOLD:
        print(
            f"\nValidation metric ({final_auc}) exceeds threshold ({TARGET_THRESHOLD}). Generating submission..."
        )

        # Aggregate Test Predictions
        avg_test_preds = np.mean(ensemble_test_preds, axis=0)

        # Create Submission DataFrame
        clips = test_dataset.clips
        submission_df = pd.DataFrame({"clip": clips, "probability": avg_test_preds})

        # Save
        submission_df.to_csv(Config.SUBMISSION_PATH, index=False)
        print(f"Submission saved to {Config.SUBMISSION_PATH}")
        print(submission_df.head())
    else:
        print(
            f"\nValidation metric ({final_auc}) did not meet threshold ({TARGET_THRESHOLD}). Skipping submission."
        )


if __name__ == "__main__":
    main()
