import os
import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score

# Import provided library modules
from library.config import Config
from library.utils import set_seed
from library.engine import Engine
from library.data_loader import DataLoader


def main():
    # 1. Setup and Initialization
    set_seed(Config.RANDOM_SEED)
    engine = Engine()
    data_loader = DataLoader()

    print("Initializing OASF Strategy Execution...")

    # 2. Run Cross-Validation
    # This trains the models using the OASF pipeline (MiniLM + Orthogonalized MPNet + Metadata)
    # and generates OOF predictions for the full labeled dataset.
    # We use load_cached_data=True to utilize any pre-computed features/embeddings.
    engine.run_cross_validation(load_cached_data=True)

    # 3. Calculate Final Validation Metric
    # We need to isolate the metrics for the hold-out validation set (val.csv).

    # Load OOF predictions and targets generated by the Engine
    oof_preds_path = os.path.join(Config.WORKING_DIR, "oof_preds.npy")
    y_path = os.path.join(Config.WORKING_DIR, "y_train_full_assembled.npy")

    if not os.path.exists(oof_preds_path) or not os.path.exists(y_path):
        raise FileNotFoundError("OOF predictions or targets not found. CV failed.")

    oof_preds = np.load(oof_preds_path)
    y_full = np.load(y_path)

    # Determine the split index between Train and Validation sets
    # The Engine concatenates [Train, Val], so we need the length of the Train set.
    df_train = data_loader.load_dataset("train", load_cached_data=True)
    df_val = data_loader.load_dataset("val", load_cached_data=True)

    split_idx = len(df_train)

    # Extract Validation Subset
    y_val_true = y_full[split_idx:]
    y_val_pred = oof_preds[split_idx:]

    # Compute AUC
    val_auc = roc_auc_score(y_val_true, y_val_pred)

    # Print the required metric
    print(f"Final Validation Metric: {val_auc}")

    # 4. Failure Analysis on Validation Set
    print("\nPerforming Failure Analysis on Validation Set...")

    # Calculate Error Magnitude
    error_magnitude = np.abs(y_val_true - y_val_pred)

    # Correlate Error with Metadata Features
    # We use the metadata columns defined in Config, plus text length
    analysis_df = df_val.copy()

    # Ensure text length is available
    if "text_combined" in analysis_df.columns:
        analysis_df["text_length"] = analysis_df["text_combined"].astype(str).apply(len)
    else:
        # Fallback if text_combined isn't in df_val (it is added in DataLoader)
        # Reconstruct it if necessary, but DataLoader adds it.
        pass

    # List of features to check
    features_to_check = Config.METADATA_COLS + ["text_length"]

    correlations = {}
    for feat in features_to_check:
        if feat in analysis_df.columns:
            # Ensure numeric and handle NaNs
            feat_values = (
                pd.to_numeric(analysis_df[feat], errors="coerce").fillna(0).values
            )

            if len(feat_values) == len(error_magnitude):
                # Calculate Pearson Correlation
                corr = np.corrcoef(feat_values, error_magnitude)[0, 1]
                correlations[feat] = corr

    # Sort and Print Correlations
    sorted_corrs = sorted(correlations.items(), key=lambda x: abs(x[1]), reverse=True)
    print("Correlation between Model Error and Input Features:")
    for feat, corr in sorted_corrs:
        print(f"{feat}: {corr:.6f}")

    # 5. Submission Generation
    threshold = 0.7190361601447052

    if val_auc > threshold:
        print(f"\nValidation metric ({val_auc}) exceeds threshold ({threshold}).")
        print("Generating submission for test set...")
        engine.predict_test(load_cached_data=True)
    else:
        print(
            f"\nValidation metric ({val_auc}) does not exceed threshold ({threshold})."
        )
        print("Skipping submission generation.")


if __name__ == "__main__":
    main()
