import os
import sys
import torch
import pandas as pd
import numpy as np
import cv2
from nltk.metrics import edit_distance

# Import from provided library files
from library.config import Config
from library.utils import seed_everything, compute_levenshtein
from library.tokenizer import Tokenizer
from library.dataset import get_train_val_loaders, get_test_loader
from library.model import InChIModel
from library.trainer import Trainer


def main():
    # -------------------------------------------------------------------------
    # 1. Setup & Configuration
    # -------------------------------------------------------------------------
    print("--- Setting up Configuration ---")
    config = Config()

    # Fast Baseline Settings
    config.debug = True
    config.debug_sample_size = 20000  # Train on a subset to ensure speed
    config.epochs = 2  # Few epochs for baseline
    config.batch_size = 128  # Efficient for A100
    config.num_workers = 12

    # Ensure reproducibility
    seed_everything(config.seed)

    print(f"Device: {config.device}")
    print(f"Debug Mode: {config.debug}")
    print(f"Epochs: {config.epochs}")

    # -------------------------------------------------------------------------
    # 2. Tokenizer & Data Loading
    # -------------------------------------------------------------------------
    print("\n--- Initializing Tokenizer & Data Loaders ---")
    # Load cached vocab if available (generated by previous steps/ideas)
    tokenizer = Tokenizer(config, load_cached_data=True)
    print(f"Vocabulary Size: {len(tokenizer)}")

    train_loader, val_loader = get_train_val_loaders(config, tokenizer)
    print(f"Train Batches: {len(train_loader)}")
    print(f"Val Batches:   {len(val_loader)}")

    # -------------------------------------------------------------------------
    # 3. Model Initialization
    # -------------------------------------------------------------------------
    print("\n--- Initializing Model ---")
    model = InChIModel(config, vocab_size=len(tokenizer))
    model.to(config.device)

    # -------------------------------------------------------------------------
    # 4. Training
    # -------------------------------------------------------------------------
    print("\n--- Starting Training ---")
    trainer = Trainer(
        model=model,
        tokenizer=tokenizer,
        config=config,
        train_loader=train_loader,
        val_loader=val_loader,
    )
    trainer.fit()

    # -------------------------------------------------------------------------
    # 5. Validation Assessment & Failure Analysis
    # -------------------------------------------------------------------------
    print("\n--- Executing Validation & Failure Analysis ---")

    # Load best model for analysis
    best_ckpt_path = os.path.join(config.checkpoint_dir, "model_best.pth")
    if os.path.exists(best_ckpt_path):
        print(f"Loading best checkpoint from {best_ckpt_path}")
        checkpoint = torch.load(best_ckpt_path, map_location=config.device)
        model.load_state_dict(checkpoint["state_dict"])
    else:
        print("Warning: Best checkpoint not found. Using current model state.")

    model.eval()

    # We need to manually run validation to collect per-sample metrics for failure analysis
    # (The trainer.validate() only returns the mean score)
    predictions = []
    ground_truths = []
    lev_distances = []

    sos_idx = tokenizer.stoi[config.sos_token]
    eos_idx = tokenizer.stoi[config.eos_token]

    print("Generating validation predictions...")
    with torch.no_grad():
        for batch_idx, (images, labels, lengths) in enumerate(val_loader):
            images = images.to(config.device)

            # Generate sequences
            gen_indices = model.generate(
                images,
                max_len=config.max_text_length,
                sos_token_idx=sos_idx,
                eos_token_idx=eos_idx,
            )

            # Decode
            for i in range(images.size(0)):
                pred_seq = gen_indices[i].cpu().numpy()
                pred_text = tokenizer.sequence_to_text(pred_seq)

                gt_seq = labels[i].cpu().numpy()
                gt_text = tokenizer.sequence_to_text(gt_seq)

                dist = edit_distance(pred_text, gt_text)

                predictions.append(pred_text)
                ground_truths.append(gt_text)
                lev_distances.append(dist)

    # Compute and Print Final Metric
    final_metric = sum(lev_distances) / len(lev_distances) if lev_distances else 0.0
    print(f"Final Validation Metric: {final_metric}")

    # Failure Analysis: Correlation with input features
    print("Performing failure analysis...")

    # Re-load validation dataframe to get metadata
    val_df = pd.read_csv(config.val_metadata_path)
    if config.debug:
        # Replicate the sampling logic from dataset.py to align rows
        val_df = val_df.sample(
            n=min(len(val_df), config.debug_sample_size), random_state=config.seed
        ).reset_index(drop=True)

    # Ensure alignment (loader might drop last batch if configured, though val usually doesn't)
    # val_loader in dataset.py has drop_last=False, so alignment should be exact.
    # However, let's truncate df to match predictions just in case.
    if len(val_df) > len(lev_distances):
        val_df = val_df.iloc[: len(lev_distances)]

    val_df["lev_dist"] = lev_distances
    val_df["inchi_len"] = val_df["InChI"].str.len()

    # Collect image dimensions for correlation analysis
    # We read a subset if the validation set is huge, but here it's 20k max (debug) or full.
    # Reading 20k images is fast enough.
    widths = []
    heights = []

    print(f"Reading image metadata for {len(val_df)} samples...")
    for idx, row in val_df.iterrows():
        path = os.path.join(config.input_root, row["file_path"])
        # Just read header/shape if possible, but cv2 reads full.
        # Given time constraints, we'll read full.
        try:
            img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
            if img is not None:
                h, w = img.shape
                widths.append(w)
                heights.append(h)
            else:
                widths.append(0)
                heights.append(0)
        except:
            widths.append(0)
            heights.append(0)

    val_df["width"] = widths
    val_df["height"] = heights

    # Calculate Correlations
    corr_len = val_df["lev_dist"].corr(val_df["inchi_len"])
    corr_width = val_df["lev_dist"].corr(val_df["width"])
    corr_height = val_df["lev_dist"].corr(val_df["height"])

    print("\nCorrelation Analysis (Error Magnitude vs Variables):")
    print(f"Correlation (Error vs InChI Length): {corr_len:.4f}")
    print(f"Correlation (Error vs Image Width):  {corr_width:.4f}")
    print(f"Correlation (Error vs Image Height): {corr_height:.4f}")

    # -------------------------------------------------------------------------
    # 6. Submission Generation
    # -------------------------------------------------------------------------
    print("\n--- Generating Submission for Full Test Set ---")

    # Switch off debug to load the FULL test set
    config.debug = False

    # Get test loader
    test_loader = get_test_loader(config, tokenizer)
    print(f"Test Loader Samples: {len(test_loader.dataset)}")

    # Update trainer with test loader and run prediction
    trainer.test_loader = test_loader
    trainer.predict()

    print("\nPipeline completed successfully.")


if __name__ == "__main__":
    main()
