import os
import sys
import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score

# Import from provided library files
from library.config import Config
from library.utils import setup_logger, load_pickle, set_seed
from library.embeddings import EmbeddingGenerator
from library.feature_engineering import assemble_features
from library.model_trainer import train_model


def main():
    # 1. Setup
    logger = setup_logger("runfile")
    set_seed(Config.SEED)
    logger.info(
        "Starting execution of Context-Aware Asymmetric Early Fusion (CAAEF) pipeline."
    )

    # 2. Generate Embeddings (Pre-compute)
    # This utilizes the GPU to generate embeddings for Train, Val, and Test splits
    logger.info("Step 1: Generating Embeddings...")
    emb_gen = EmbeddingGenerator()
    emb_gen.generate_all(load_cached_data=True)

    # 3. Train Model
    # This runs 5-Fold CV, saves models, and generates the submission file
    logger.info("Step 2: Training Model...")
    final_metric = train_model(load_cached_data=True)

    # 4. Report Metric
    # Required format: Final Validation Metric: <value>
    print(f"Final Validation Metric: {final_metric}")

    # 5. Failure Analysis
    logger.info("Step 3: Performing Failure Analysis...")

    # Load data to reconstruct OOF predictions
    # We need the exact same data assembly as used in model_trainer
    X_train_part, y_train_part = assemble_features("train", load_cached_data=True)
    X_val_part, y_val_part = assemble_features("val", load_cached_data=True)

    # Stack to match the CV process
    X = np.vstack([X_train_part, X_val_part])
    y = np.hstack([y_train_part, y_val_part])

    # Re-create the split
    skf = StratifiedKFold(
        n_splits=Config.N_FOLDS, shuffle=True, random_state=Config.SEED
    )
    oof_preds = np.zeros(len(y))

    # Iterate folds to generate unbiased predictions using the saved models
    for fold, (train_idx, val_idx) in enumerate(skf.split(X, y)):
        model_path = os.path.join(Config.WORKING_DIR, f"model_fold_{fold}.joblib")

        if not os.path.exists(model_path):
            logger.warning(
                f"Model file {model_path} not found. Skipping failure analysis for this fold."
            )
            continue

        pipeline = load_pickle(model_path)

        # Predict on validation fold
        X_val_fold = X[val_idx]
        preds = pipeline.predict_proba(X_val_fold)[:, 1]
        oof_preds[val_idx] = preds

    # Calculate Error
    errors = np.abs(y - oof_preds)

    # Extract Metadata features for correlation analysis
    # Structure of X is [Anchor (384) | Aux (768) | Metadata (...)]
    # We use the dimensions from Config to slice
    # Note: We need to know the dimensions.
    # MiniLM-L6-v2 is 384, MPNet-base-v2 is 768.
    anchor_dim = 384
    aux_dim = 768
    start_meta = anchor_dim + aux_dim

    X_meta = X[:, start_meta:]

    # Create DataFrame for analysis
    # Ensure column count matches
    if X_meta.shape[1] == len(Config.NUMERIC_COLS):
        df_analysis = pd.DataFrame(X_meta, columns=Config.NUMERIC_COLS)
        df_analysis["error"] = errors

        logger.info("Calculating correlations between features and error magnitude...")
        correlations = (
            df_analysis.corr()["error"].drop("error").sort_values(ascending=False)
        )

        print("\nFailure Analysis - Correlation with Error:")
        print(correlations)
    else:
        logger.warning(
            f"Metadata feature count mismatch. Expected {len(Config.NUMERIC_COLS)}, got {X_meta.shape[1]}. Skipping correlation detail."
        )

    # 6. Submission Management
    # The submission file is generated by train_model automatically.
    # We must enforce the threshold requirement.
    threshold = 0.7190361601447052

    if final_metric > threshold:
        logger.info(
            f"Validation metric {final_metric} exceeds threshold {threshold}. Submission saved."
        )
    else:
        logger.warning(
            f"Validation metric {final_metric} does not exceed threshold {threshold}."
        )
        if os.path.exists(Config.SUBMISSION_PATH):
            logger.info("Removing submission file due to low score.")
            os.remove(Config.SUBMISSION_PATH)


if __name__ == "__main__":
    main()
