import os
import shutil
import numpy as np
import pandas as pd
from library.config import Config
from library.data_processor import DataPipeline
from library.model_trainer import DualTargetRegressor


def run_demo():
    print("--- Starting Demo Execution ---")

    # 1. Configuration Override for Speed and Isolation
    # We modify the Config class attributes directly to create a lightweight demo environment.
    print("Configuring demo parameters...")
    Config.SAMPLE_SIZE = 50  # Process only 50 samples to ensure speed
    Config.WORKING_DIR = (
        "./working/demo_execution"  # Use a separate directory for demo outputs
    )
    Config.XGB_PARAMS["n_estimators"] = 10  # Reduce boosting rounds for speed
    Config.XGB_PARAMS["n_jobs"] = 4  # Use reasonable parallelism

    # Update derived paths in Config to reflect the new WORKING_DIR
    Config.TRAIN_FEATURES_PATH = os.path.join(
        Config.WORKING_DIR, "train_features.parquet"
    )
    Config.VAL_FEATURES_PATH = os.path.join(Config.WORKING_DIR, "val_features.parquet")
    Config.TEST_FEATURES_PATH = os.path.join(
        Config.WORKING_DIR, "test_features.parquet"
    )

    # Ensure the demo working directory exists
    os.makedirs(Config.WORKING_DIR, exist_ok=True)

    # 2. Data Loading and Feature Extraction
    # We instantiate the DataPipeline and load data.
    # load_cached_data=False forces the pipeline to run feature extraction on the sample subset.
    print("\n--- Step 1: Data Loading & Feature Extraction ---")
    pipeline = DataPipeline()

    # Note: This step uses ase.io.read and the custom FeatureExtractor (including MatGL)
    train_df, val_df, test_df = pipeline.load_data(load_cached_data=False)

    # 3. Verification of Data Processing
    print("\n--- Step 2: Verifying Data Integrity ---")

    # Check if dataframes are populated
    assert not train_df.empty, "Training dataframe is empty."
    assert not val_df.empty, "Validation dataframe is empty."
    assert not test_df.empty, "Test dataframe is empty."

    print(f"Train shape: {train_df.shape}")
    print(f"Val shape:   {val_df.shape}")
    print(f"Test shape:  {test_df.shape}")

    # Check for expected feature columns generated by descriptors.py
    # Physical properties
    assert "phys_volume" in train_df.columns, "Physical feature 'phys_volume' missing."
    assert (
        "phys_density" in train_df.columns
    ), "Physical feature 'phys_density' missing."

    # RDF features (checking for at least one bin)
    # Note: The exact column name depends on elements present, but 'rdf_' prefix is constant.
    rdf_cols = [c for c in train_df.columns if c.startswith("rdf_")]
    assert len(rdf_cols) > 0, "RDF features were not generated."

    # MatGL Embeddings (checking for anion/cation embeddings)
    # If MatGL loaded successfully, these should exist.
    emb_cols = [c for c in train_df.columns if c.startswith("emb_")]
    if len(emb_cols) > 0:
        print(f"Verified {len(emb_cols)} sublattice embedding features.")
    else:
        print(
            "Warning: MatGL embeddings not found (possibly due to model load failure), but proceeding."
        )

    # Check for targets in training data
    for target in Config.TARGET_COLS:
        assert (
            target in train_df.columns
        ), f"Target '{target}' missing from training data."
        assert (
            target in val_df.columns
        ), f"Target '{target}' missing from validation data."

    # 4. Model Training
    print("\n--- Step 3: Model Training ---")
    trainer = DualTargetRegressor()

    # Fit the models (Formation Energy and Bandgap)
    trainer.fit(train_df, val_df)

    # Verify that feature columns were captured
    assert (
        trainer.feature_cols is not None
    ), "Trainer failed to identify feature columns."
    assert len(trainer.feature_cols) > 0, "No features selected for training."

    # 5. Evaluation
    print("\n--- Step 4: Evaluation ---")
    rmsle_score = trainer.evaluate(val_df)

    # Basic sanity check on the score (it should be a non-negative float)
    assert isinstance(rmsle_score, float), "RMSLE score is not a float."
    assert rmsle_score >= 0, "RMSLE score cannot be negative."
    print(f"Validation RMSLE verified: {rmsle_score:.4f}")

    # 6. Prediction and Submission
    print("\n--- Step 5: Prediction & Submission ---")
    submission_df = trainer.predict(test_df)

    # Verify submission format
    expected_cols = ["id"] + Config.TARGET_COLS
    assert (
        list(submission_df.columns) == expected_cols
    ), f"Submission columns mismatch. Expected {expected_cols}, got {list(submission_df.columns)}"
    assert len(submission_df) == len(
        test_df
    ), "Submission row count does not match test set size."

    # Check for non-negative predictions (physics constraint enforced by expm1)
    assert (
        (submission_df[Config.TARGET_COLS] >= 0).all().all()
    ), "Negative predictions found, inverse transform failed."

    # Save submission
    trainer.save_submission(submission_df)

    # Verify file creation
    assert os.path.exists(Config.SUBMISSION_PATH), "Submission file was not created."
    print(f"Submission file verified at: {Config.SUBMISSION_PATH}")

    print("\n--- Demo Execution Completed Successfully ---")


if __name__ == "__main__":
    run_demo()
