import os
import numpy as np
import pandas as pd
import warnings
import gc

# Import library modules
import library.config as config
import library.utils as utils
from library.training_pipeline import TrainingPipeline
from library.inference_pipeline import InferencePipeline
from library.physics_engine import FeatureManager
from library.model_factory import TriEnsemble

# Suppress warnings for cleaner output
warnings.filterwarnings("ignore")


def main():
    # ---------------------------------------------------------
    # 1. Setup and Configuration
    # ---------------------------------------------------------
    # Set seed for reproducibility
    np.random.seed(config.SEED)

    # Override submission directory to match task requirements
    config.SUBMISSION_DIR = "./submission"
    os.makedirs(config.SUBMISSION_DIR, exist_ok=True)

    print("Initializing VASM-E Runfile...")

    # ---------------------------------------------------------
    # 2. Training Pipeline (Fast Baseline)
    # ---------------------------------------------------------
    # We use a debug_sample to ensure the code runs within the time limit.
    # 200,000 samples is sufficient for a robust baseline check.
    DEBUG_SAMPLE_SIZE = 200000

    trainer = TrainingPipeline()

    # Execute training pipeline
    # This handles: Feature Engineering, Scout Training, Hard Negative Mining, and Expert Training
    # Returns the best MCC from the internal validation phase
    print(f"Executing Training Pipeline with {DEBUG_SAMPLE_SIZE} samples...")
    _ = trainer.run(debug_sample=DEBUG_SAMPLE_SIZE, load_cached_data=True)

    # ---------------------------------------------------------
    # 3. Validation & Failure Analysis
    # ---------------------------------------------------------
    print("\nLoading validation data for Failure Analysis...")

    # Reload validation data (reusing the cache generated by the pipeline)
    fm = FeatureManager()
    df_val = fm.process_data(split="val", load_cached_data=True)

    # Load the trained expert model
    model = TriEnsemble.load("expert_ensemble.joblib")

    # Load the optimized threshold
    thresh_path = os.path.join(config.MODEL_DIR, "best_threshold.npy")
    if os.path.exists(thresh_path):
        best_threshold = float(np.load(thresh_path))
    else:
        best_threshold = 0.5

    # Prepare Validation Features
    X_val = df_val[config.MODEL_FEATURES]
    y_val = df_val["contact"].values

    # Generate Predictions
    print("Generating validation predictions...")
    val_probs = model.predict_proba(X_val)

    # Calculate and Print Final Metric
    final_mcc = utils.calc_mcc(y_val, val_probs, best_threshold)
    print(f"Final Validation Metric: {final_mcc}")

    # Failure Analysis: Correlation between Error Magnitude and Features
    print("\n--- Failure Analysis ---")
    # Error magnitude: |y_true - y_pred_prob|
    errors = np.abs(y_val - val_probs)

    print("Correlation between Error Magnitude and Features:")
    correlations = {}
    for col in config.MODEL_FEATURES:
        if col in X_val.columns:
            feat_values = X_val[col].values
            # Avoid correlation calculation if feature is constant
            if np.std(feat_values) > 1e-9:
                corr = np.corrcoef(feat_values, errors)[0, 1]
                correlations[col] = corr
            else:
                correlations[col] = 0.0

    # Sort by absolute correlation and print
    sorted_corr = sorted(correlations.items(), key=lambda x: abs(x[1]), reverse=True)
    for feat, corr in sorted_corr:
        print(f"{feat}: {corr:.4f}")

    # ---------------------------------------------------------
    # 4. Submission Generation
    # ---------------------------------------------------------
    THRESHOLD_SCORE = 0.6865

    if final_mcc > THRESHOLD_SCORE:
        print(
            f"\nValidation MCC ({final_mcc:.4f}) > {THRESHOLD_SCORE}. Generating submission..."
        )

        inferencer = InferencePipeline()
        # Run inference on the full test set (debug_sample=None implies full set)
        submission_path = inferencer.run(load_cached_data=True, debug_sample=None)

        print(f"Submission generation complete: {submission_path}")
    else:
        print(
            f"\nValidation MCC ({final_mcc:.4f}) <= {THRESHOLD_SCORE}. Skipping submission."
        )

    # Explicit garbage collection
    del df_val, X_val, val_probs, model
    gc.collect()


if __name__ == "__main__":
    main()
