import os
import torch
import torch.optim as optim
import pandas as pd
import numpy as np
import random
import shutil

# Import from the provided library
from library.config import Config
from library.utils import build_vocab
from library.data import get_dataloaders, preprocess_data
from library.model import SingleStreamNetwork
from library.engine import Engine


def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def main():
    print("--- Starting Single-Stream Network Demonstration ---")

    # 1. Setup and Configuration Override
    # We override config parameters to ensure the demo runs quickly and uses a separate workspace
    Config.WORKING_DIR = "./working/demo_run_idea_9"
    Config.CACHE_DIR = Config.WORKING_DIR
    Config.SUBMISSION_DIR = "./working/demo_submission"

    # Update paths based on new directories
    Config.VOCAB_CACHE_PATH = os.path.join(Config.CACHE_DIR, "vocab.npy")
    Config.EMBEDDING_MATRIX_CACHE_PATH = os.path.join(
        Config.CACHE_DIR, "embedding_matrix.npy"
    )
    Config.PROCESSED_TRAIN_DATA_PATH = os.path.join(
        Config.CACHE_DIR, "train_data.parquet"
    )
    Config.PROCESSED_VAL_DATA_PATH = os.path.join(Config.CACHE_DIR, "val_data.parquet")
    Config.PROCESSED_TEST_DATA_PATH = os.path.join(
        Config.CACHE_DIR, "test_data.parquet"
    )
    Config.SUBMISSION_PATH = os.path.join(Config.SUBMISSION_DIR, "submission.csv")

    # Hyperparameters for speed
    Config.NUM_EPOCHS = 1
    Config.BATCH_SIZE = 4
    Config.DATASET_FRACTION = 0.005  # Use 0.5% of data for demo
    Config.VOCAB_SIZE = 1000  # Small vocab for speed
    Config.EMBEDDING_DIM = 64
    Config.HIDDEN_DIM = 64

    # Create directories
    os.makedirs(Config.WORKING_DIR, exist_ok=True)
    os.makedirs(Config.SUBMISSION_DIR, exist_ok=True)

    set_seed(Config.SEED)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    # 2. Data Loading
    print("\n--- Loading Data ---")
    # We set load_cached_data=False to force processing the small subset defined by DATASET_FRACTION
    train_loader, val_loader, test_loader, vocab = get_dataloaders(
        load_cached_data=False, debug=True
    )

    print(f"Vocabulary size: {len(vocab)}")
    print(f"Train batches: {len(train_loader)}")
    print(f"Val batches: {len(val_loader)}")
    print(f"Test batches: {len(test_loader)}")

    # Verify Data
    assert len(vocab) > 0, "Vocabulary should not be empty"
    assert len(train_loader) > 0, "Train loader should not be empty"

    # Get test dataframe for inference mapping (Engine.predict needs it)
    # We load it from the cache generated by get_dataloaders to ensure consistency
    test_df = pd.read_parquet(Config.PROCESSED_TEST_DATA_PATH)
    assert not test_df.empty, "Test DataFrame should not be empty"

    # 3. Model Initialization
    print("\n--- Initializing Model ---")
    model = SingleStreamNetwork(vocab).to(device)

    # Verify Model Forward Pass with a dummy batch
    dummy_batch = next(iter(train_loader))
    dummy_input = dummy_batch["input_ids"].to(device)

    print(f"Dummy input shape: {dummy_input.shape}")
    with torch.no_grad():
        dummy_output = model(dummy_input)

    # Check output shapes
    # Ranking logits: (Batch,)
    assert dummy_output["ranking_logits"].shape == (
        dummy_input.shape[0],
    ), f"Ranking logits shape mismatch: {dummy_output['ranking_logits'].shape}"
    # Span logits: (Batch, Seq_Len)
    assert (
        dummy_output["start_logits"].shape == dummy_input.shape
    ), f"Start logits shape mismatch: {dummy_output['start_logits'].shape}"
    # Yes/No logits: (Batch, Num_Classes)
    assert dummy_output["yes_no_logits"].shape == (
        dummy_input.shape[0],
        Config.NUM_YES_NO_CLASSES,
    ), f"Yes/No logits shape mismatch: {dummy_output['yes_no_logits'].shape}"

    print("Model forward pass verified.")

    # 4. Training
    print("\n--- Starting Training ---")
    optimizer = optim.Adam(model.parameters(), lr=Config.LEARNING_RATE)
    engine = Engine(model, device, optimizer)

    for epoch in range(Config.NUM_EPOCHS):
        train_loss = engine.train_one_epoch(train_loader)
        val_metrics = engine.validate(val_loader)

        print(f"Epoch {epoch+1}/{Config.NUM_EPOCHS}")
        print(f"  Train Loss: {train_loss:.4f}")
        print(f"  Val Loss:   {val_metrics['val_loss']:.4f}")
        print(f"  Val Rank Acc: {val_metrics['val_rank_acc']:.4f}")

        # Basic assertion to ensure loss is valid
        assert not np.isnan(train_loss), "Training loss is NaN"
        assert train_loss > 0, "Training loss should be positive"

    # 5. Inference
    print("\n--- Running Inference ---")
    # Define submission path explicitly here to ensure we check the right file
    submission_file = Config.SUBMISSION_PATH
    if os.path.exists(submission_file):
        os.remove(submission_file)

    engine.predict(test_loader, test_df)

    # 6. Verification of Submission
    print("\n--- Verifying Submission ---")
    assert os.path.exists(submission_file), "Submission file was not created"

    sub_df = pd.read_csv(submission_file)
    print(f"Submission shape: {sub_df.shape}")
    print("First 5 rows:")
    print(sub_df.head())

    # Check format
    assert "example_id" in sub_df.columns, "Missing example_id column"
    assert "PredictionString" in sub_df.columns, "Missing PredictionString column"

    # Check if we have predictions for both long and short per example
    # Input test file has ~30k examples. We processed all of them.
    # The submission should have 2 * num_test_examples rows.
    # We can check against the test_df we loaded.
    expected_rows = len(test_df) * 2
    assert (
        len(sub_df) == expected_rows
    ), f"Submission row count mismatch. Expected {expected_rows}, got {len(sub_df)}"

    print("\n--- Demonstration Completed Successfully ---")


if __name__ == "__main__":
    main()
