import os
import sys
import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score
from scipy.stats import pearsonr

# Import library components
from library.config import Config
from library.training_engine import TrainingEngine
from library.inference_engine import InferenceEngine
from library.model_zoo import get_meta_learner
from library.utils import set_seed


def main():
    # 1. Setup
    set_seed(Config.SEED)
    print("Initializing Pipeline...")

    # 2. Training Phase
    # This generates OOF predictions and trains stable models on the Union dataset
    print("\n" + "=" * 40)
    print("Step 1: Training & OOF Generation")
    print("=" * 40)
    trainer = TrainingEngine()
    trainer.run()

    # 3. Validation Phase
    print("\n" + "=" * 40)
    print("Step 2: Validation & Metric Calculation")
    print("=" * 40)

    # Load original metadata to identify split indices
    # The DataManager concatenates Train then Val, so we use the length of Train to split
    if not os.path.exists(Config.TRAIN_PATH) or not os.path.exists(Config.VAL_PATH):
        raise FileNotFoundError(
            "Metadata files missing. Ensure ./metadata/train.parquet exists."
        )

    train_meta = pd.read_parquet(Config.TRAIN_PATH)
    val_meta = pd.read_parquet(Config.VAL_PATH)

    n_train = len(train_meta)

    # Load OOF predictions generated by TrainingEngine
    oof_path = os.path.join(Config.WORKING_DIR, "oof_predictions.csv")
    if not os.path.exists(oof_path):
        raise FileNotFoundError("OOF predictions not found. Training may have failed.")

    oof_df = pd.read_csv(oof_path)

    # Split OOFs back into Train and Val segments
    # DataManager concats train then val, so we split by length
    train_oofs = oof_df.iloc[:n_train].copy()
    val_oofs = oof_df.iloc[n_train:].reset_index(drop=True)

    # Define base model columns expected by the Meta-Learner
    feature_cols = [
        "lexical_bagger",
        "community_bagger",
        "semantic_booster",
        "semantic_gradient",
        "semantic_bagger",
        "metadata_anchor",
        "temporal_booster",
    ]

    # Train a temporary Meta-Learner on Train OOFs to evaluate on Val OOFs
    # This simulates the hold-out validation scenario
    print("Training Validation Meta-Learner...")
    X_meta_train = train_oofs[feature_cols].values
    y_meta_train = train_oofs["requester_received_pizza"].values

    X_meta_val = val_oofs[feature_cols].values
    y_meta_val = val_oofs["requester_received_pizza"].values

    val_meta_learner = get_meta_learner()
    val_meta_learner.fit(X_meta_train, y_meta_train)

    # Predict on Validation set
    val_preds = val_meta_learner.predict_proba(X_meta_val)[:, 1]

    # Calculate Metric
    final_auc = roc_auc_score(y_meta_val, val_preds)
    print(f"Final Validation Metric: {final_auc}")

    # 4. Failure Analysis
    print("\n" + "=" * 40)
    print("Step 3: Failure Analysis")
    print("=" * 40)

    # Calculate error
    # Ensure indices align
    val_meta = val_meta.reset_index(drop=True)
    val_meta["prediction"] = val_preds
    val_meta["error"] = np.abs(
        val_meta["requester_received_pizza"] - val_meta["prediction"]
    )

    # Correlate error with numerical features
    print("Top correlations with Error Magnitude:")
    numerical_cols = val_meta.select_dtypes(include=[np.number]).columns
    correlations = []

    for col in numerical_cols:
        if col in ["requester_received_pizza", "prediction", "error"]:
            continue
        # Handle NaNs just in case
        series = val_meta[col].fillna(0)
        # Only correlate if there is variance
        if series.nunique() > 1:
            corr, _ = pearsonr(series, val_meta["error"])
            if not np.isnan(corr):
                correlations.append((col, corr))

    # Sort by absolute correlation
    correlations.sort(key=lambda x: abs(x[1]), reverse=True)

    for name, corr in correlations[:5]:
        print(f"  {name}: {corr:.4f}")

    # 5. Submission
    print("\n" + "=" * 40)
    print("Step 4: Submission Generation")
    print("=" * 40)

    threshold = 0.7222984867326668
    if final_auc > threshold:
        print(
            f"Validation AUC ({final_auc}) > Threshold ({threshold}). Generating submission..."
        )
        inference = InferenceEngine()
        inference.run()
    else:
        print(
            f"Validation AUC ({final_auc}) <= Threshold ({threshold}). Skipping submission."
        )


if __name__ == "__main__":
    main()
