import os
import sys
import numpy as np
import pandas as pd
import cv2
import shutil
from scipy.stats import pearsonr
from sklearn.metrics import roc_auc_score

# Import library modules
from library.config import Config
from library.utils import seed_everything
from library.trainer import run_fold
from library.meta_learner import train_stacker
from library.inference import run_inference


def main():
    # --- 1. Setup & Configuration Overrides for Fast Baseline ---
    seed_everything(Config.SEED)

    # Define paths for temporary subset metadata
    subset_train_path = os.path.join(Config.WORKING_DIR, "train_subset.csv")
    subset_val_path = os.path.join(Config.WORKING_DIR, "val_subset.csv")

    # Load original metadata
    print("Loading original metadata for subsetting...")
    train_full = pd.read_csv(Config.TRAIN_METADATA_PATH)
    val_full = pd.read_csv(Config.VAL_METADATA_PATH)

    # Create subsets (e.g., 500 training samples, 100 validation samples)
    # This ensures the pipeline runs quickly within the time limit
    n_train = min(500, len(train_full))
    n_val = min(100, len(val_full))

    train_subset = train_full.sample(n=n_train, random_state=Config.SEED).reset_index(
        drop=True
    )
    val_subset = val_full.sample(n=n_val, random_state=Config.SEED).reset_index(
        drop=True
    )

    # Save subsets
    train_subset.to_csv(subset_train_path, index=False)
    val_subset.to_csv(subset_val_path, index=False)

    # Override Config attributes to use subsets and reduce training time
    Config.TRAIN_METADATA_PATH = subset_train_path
    Config.VAL_METADATA_PATH = subset_val_path
    Config.EPOCHS = 1  # Reduce to 1 epoch for fast baseline
    Config.N_FOLDS = 2  # Run only 2 folds instead of 5

    # Clean up existing cache files to ensure fresh run with new config
    files_to_remove = [
        os.path.join(Config.WORKING_DIR, "folds.parquet"),
        os.path.join(Config.WORKING_DIR, "stacked_oof_data.parquet"),
    ]
    for f in files_to_remove:
        if os.path.exists(f):
            os.remove(f)

    print(f"Configuration updated: EPOCHS={Config.EPOCHS}, N_FOLDS={Config.N_FOLDS}")

    # --- 2. Base Model Training ---
    model_oof_preds = {}

    for model_name in Config.MODELS:
        model_oof_preds[model_name] = {}
        for fold_idx in range(Config.N_FOLDS):
            # Train the model for this fold
            # run_fold returns (model, oof_preds, val_labels)
            _, oof_preds, _ = run_fold(fold_idx, model_name)

            # Store OOF predictions
            model_oof_preds[model_name][fold_idx] = oof_preds

    # --- 3. Stacking Ensemble Training ---
    print("\n--- Training Stacking Meta-Learner ---")
    # Train stacker using the collected OOF predictions
    # load_cached_data=False forces regeneration of the stacking dataset
    meta_learner = train_stacker(
        model_oof_preds=model_oof_preds, load_cached_data=False
    )

    # --- 4. Validation Assessment ---
    print("\n--- Validation Assessment ---")
    # Load the stacked OOF data generated by train_stacker
    # This contains the predictions from base models and the ground truth
    df_oof = pd.read_parquet(
        os.path.join(Config.WORKING_DIR, "stacked_oof_data.parquet")
    )

    # Generate final probabilities using the meta-learner
    feature_cols = [f"pred_{m}" for m in Config.MODELS]
    X_oof = df_oof[feature_cols].values

    # StackingMetaLearner.predict returns probabilities of class 1
    df_oof["final_prob"] = meta_learner.predict(X_oof)

    # Filter results to include only the hold-out validation set
    # We identify validation samples by their IDs from the val_subset
    val_ids = val_subset["id"].values
    df_val_results = df_oof[df_oof["id"].isin(val_ids)].copy()

    if len(df_val_results) == 0:
        print("Warning: No validation samples found in OOF data. Using all OOF data.")
        df_val_results = df_oof

    # Calculate Validation Metric
    val_auc = roc_auc_score(df_val_results["label"], df_val_results["final_prob"])
    print(f"Final Validation Metric: {val_auc}")

    # --- 5. Failure Analysis ---
    print("\n--- Failure Analysis ---")
    # Calculate absolute error
    df_val_results["error"] = np.abs(
        df_val_results["label"] - df_val_results["final_prob"]
    )

    # Compute image features for correlation analysis
    errors = []
    brightness_means = []
    contrast_stds = []

    print("Analyzing systematic errors...")
    for idx, row in df_val_results.iterrows():
        # Get file path
        # Note: df_val_results might not have file_path, look up in val_subset
        match = val_subset[val_subset["id"] == row["id"]]
        if match.empty:
            continue

        rel_path = match.iloc[0]["file_path"]
        full_path = os.path.join(Config.INPUT_DIR, rel_path)

        if not os.path.exists(full_path):
            continue

        # Read image
        img = cv2.imread(full_path)
        if img is None:
            continue

        # Convert to RGB
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        # Calculate stats
        mean_val = img.mean()
        std_val = img.std()

        errors.append(row["error"])
        brightness_means.append(mean_val)
        contrast_stds.append(std_val)

    # Calculate correlations
    if len(errors) > 1:
        corr_brightness, _ = pearsonr(errors, brightness_means)
        corr_contrast, _ = pearsonr(errors, contrast_stds)

        print(f"Correlation between Error and Image Brightness: {corr_brightness:.4f}")
        print(f"Correlation between Error and Image Contrast: {corr_contrast:.4f}")
    else:
        print("Insufficient data for correlation analysis.")

    # --- 6. Submission Generation ---
    THRESHOLD = 0.9933607469455475

    if val_auc > THRESHOLD:
        print(
            f"\nValidation AUC ({val_auc}) exceeds threshold ({THRESHOLD}). Generating submission..."
        )

        # Clear cached test predictions to ensure consistency
        for m in Config.MODELS:
            cache_p = os.path.join(Config.WORKING_DIR, f"test_preds_{m}.npy")
            if os.path.exists(cache_p):
                os.remove(cache_p)

        # Run inference
        run_inference(load_cached_data=False)
    else:
        print(
            f"\nValidation AUC ({val_auc}) did not exceed threshold ({THRESHOLD}). Submission skipped."
        )


if __name__ == "__main__":
    main()
