import os
import shutil
import pandas as pd
import numpy as np
import torch
import lightgbm as lgb
from library.config import Config
from library.utils import set_seed, calc_kendall_tau
from library.data_loader import RelaxedProximityDataset
from library.fine_tuner import FineTuner
from library.feature_extractor import FeatureEngineer
from library.regressor import RankRegressor
from library.inference import Predictor, generate_submission


def run_demo():
    # =========================================================================
    # 1. Setup & Configuration Override
    # =========================================================================
    print(">>> [1/6] Setting up demonstration environment...")

    # Define demo directories
    DEMO_DIR = "./working/demo_run"
    DEMO_METADATA_DIR = os.path.join(DEMO_DIR, "metadata")

    # Clean up previous run if exists
    if os.path.exists(DEMO_DIR):
        shutil.rmtree(DEMO_DIR)
    os.makedirs(DEMO_METADATA_DIR, exist_ok=True)

    # Override Config to use demo paths and lightweight parameters
    Config.WORKING_DIR = DEMO_DIR
    Config.METADATA_DIR = DEMO_METADATA_DIR
    Config.SUBMISSION_DIR = DEMO_DIR

    # Update file paths in Config
    Config.TRAIN_METADATA_PATH = os.path.join(DEMO_METADATA_DIR, "train.csv")
    Config.VAL_METADATA_PATH = os.path.join(DEMO_METADATA_DIR, "val.csv")
    Config.TEST_METADATA_PATH = os.path.join(DEMO_METADATA_DIR, "test.csv")

    Config.TRAIN_PAIRS_PATH = os.path.join(DEMO_DIR, "train_pairs_relaxed.parquet")
    Config.TRAIN_FEATURES_PATH = os.path.join(DEMO_DIR, "train_features.parquet")
    Config.VAL_FEATURES_PATH = os.path.join(DEMO_DIR, "val_features.parquet")
    Config.TEST_FEATURES_PATH = os.path.join(DEMO_DIR, "test_features_debug.parquet")

    Config.FINE_TUNED_MODEL_PATH = os.path.join(DEMO_DIR, "dsapr_model")
    Config.LGBM_MODEL_PATH = os.path.join(DEMO_DIR, "lgbm_model.txt")
    Config.SUBMISSION_PATH = os.path.join(DEMO_DIR, "submission.csv")

    # Speed optimizations
    Config.NUM_EPOCHS = 1
    Config.BATCH_SIZE = 4
    Config.FINE_TUNE_SUBSET_SIZE = 20  # Only use 20 notebooks for fine-tuning
    Config.LGBM_PARAMS["num_leaves"] = 8  # Simpler model
    Config.LGBM_PARAMS["n_estimators"] = 10  # Very few trees for demo

    set_seed(Config.SEED)

    # Create sampled metadata files
    print("Creating sampled metadata...")
    df_train_full = pd.read_csv("./metadata/train.csv")
    df_val_full = pd.read_csv("./metadata/val.csv")
    df_test_full = pd.read_csv("./metadata/test.csv")

    # Sample 50 train, 20 val, 20 test
    df_train_sample = df_train_full.head(50)
    df_val_sample = df_val_full.head(20)
    df_test_sample = df_test_full.head(20)

    df_train_sample.to_csv(Config.TRAIN_METADATA_PATH, index=False)
    df_val_sample.to_csv(Config.VAL_METADATA_PATH, index=False)
    df_test_sample.to_csv(Config.TEST_METADATA_PATH, index=False)

    print(
        f"Sampled Train: {len(df_train_sample)}, Val: {len(df_val_sample)}, Test: {len(df_test_sample)}"
    )

    # =========================================================================
    # 2. Fine-Tuning Demonstration
    # =========================================================================
    print("\n>>> [2/6] Demonstrating Fine-Tuning (Contrastive Learning)...")

    # Initialize FineTuner
    fine_tuner = FineTuner()

    # Validate Dataset Logic
    dataset = RelaxedProximityDataset(
        metadata_path=Config.TRAIN_METADATA_PATH,
        load_cached_data=False,  # Force generation
        subset_size=Config.FINE_TUNE_SUBSET_SIZE,
    )

    if len(dataset) > 0:
        example = dataset[0]
        # Check if it returns InputExample with 2 texts (Anchor, Positive)
        assert len(example.texts) == 2, "Dataset should return pairs (Markdown, Code)"
        print(f"Dataset generated {len(dataset)} pairs. Sample pair valid.")
    else:
        print("Warning: Dataset is empty (sampled notebooks might be too small/empty).")

    # Run Training
    fine_tuner.train(
        metadata_path=Config.TRAIN_METADATA_PATH,
        subset_size=Config.FINE_TUNE_SUBSET_SIZE,
        epochs=Config.NUM_EPOCHS,
        batch_size=Config.BATCH_SIZE,
        load_cached_data=True,  # Use the cache generated by dataset init above
    )

    # Verify model artifact
    assert os.path.exists(
        Config.FINE_TUNED_MODEL_PATH
    ), "Fine-tuned model directory not created."
    print("Fine-tuning successful. Model saved.")

    # =========================================================================
    # 3. Feature Extraction Demonstration
    # =========================================================================
    print("\n>>> [3/6] Demonstrating Feature Extraction...")

    feature_engineer = FeatureEngineer()

    # Extract Train Features
    df_train_feats = feature_engineer.extract_features(
        metadata_path=Config.TRAIN_METADATA_PATH,
        save_path=Config.TRAIN_FEATURES_PATH,
        load_cached_data=False,
    )

    # Extract Val Features
    df_val_feats = feature_engineer.extract_features(
        metadata_path=Config.VAL_METADATA_PATH,
        save_path=Config.VAL_FEATURES_PATH,
        load_cached_data=False,
    )

    # Verification
    assert not df_train_feats.empty, "Train features DataFrame is empty."
    assert (
        "target" in df_train_feats.columns
    ), "Target column missing in train features."
    assert "heatmap_0" in df_train_feats.columns, "Heatmap features missing."
    print(
        f"Extracted features for {df_train_feats['id'].nunique()} training notebooks."
    )

    # =========================================================================
    # 4. Regression Training Demonstration
    # =========================================================================
    print("\n>>> [4/6] Demonstrating Rank Regressor Training...")

    regressor = RankRegressor()

    # Train model
    regressor.train(df_train_feats, df_val_feats)

    # Verify model artifact
    assert os.path.exists(Config.LGBM_MODEL_PATH), "LightGBM model file not created."

    # Test internal prediction on validation set
    val_preds = regressor.predict(df_val_feats)
    assert len(val_preds) == len(df_val_feats), "Prediction length mismatch."
    print("Regressor training and internal validation prediction successful.")

    # =========================================================================
    # 5. Inference Pipeline Demonstration
    # =========================================================================
    print("\n>>> [5/6] Demonstrating Inference Pipeline...")

    predictor = Predictor()

    # 1. Predict Test Set (Features + Regression)
    # Note: Predictor instantiates its own FeatureEngineer and Regressor
    # It will pick up the models saved in previous steps via Config paths
    df_test_preds = predictor.predict_test_set(
        test_metadata_path=Config.TEST_METADATA_PATH, load_cached_data=False
    )

    assert "pred" in df_test_preds.columns, "Prediction column missing."

    # 2. Generate Submission
    generate_submission(
        predictions_df=df_test_preds,
        test_metadata_path=Config.TEST_METADATA_PATH,
        output_path=Config.SUBMISSION_PATH,
    )

    assert os.path.exists(Config.SUBMISSION_PATH), "Submission file not created."

    # Check submission format
    df_sub = pd.read_csv(Config.SUBMISSION_PATH)
    assert list(df_sub.columns) == ["id", "cell_order"], "Submission columns incorrect."
    assert len(df_sub) == len(df_test_sample), "Submission row count mismatch."
    print("Inference pipeline completed successfully.")

    # =========================================================================
    # 6. Metric Verification
    # =========================================================================
    print("\n>>> [6/6] Verifying Metric Calculation...")

    # To verify the metric, we will treat the validation set as a "test" set
    # because we have the ground truth for it.

    # Reconstruct order for validation set based on the regressor predictions we made in step 4
    # We need to manually do what generate_submission does but for the validation set

    print("Calculating Kendall Tau on Validation Set...")
    val_pred_rows = []

    # Create prediction dict
    df_val_feats["pred"] = val_preds
    pred_dict = {}
    for nb_id, group in df_val_feats.groupby("id"):
        pred_dict[nb_id] = dict(zip(group["cell_id"], group["pred"]))

    # Reconstruct orders
    from library.utils import read_notebook

    for _, row in df_val_sample.iterrows():
        nb_id = row["id"]
        file_path = os.path.join(Config.INPUT_DIR, row["file_path"])
        try:
            code_cells, md_cells = read_notebook(file_path)
        except:
            continue

        cells_with_ranks = []
        for i, cell in enumerate(code_cells):
            cells_with_ranks.append((i + 0.5, cell["id"]))

        n_code = len(code_cells)
        nb_preds = pred_dict.get(nb_id, {})

        for cell in md_cells:
            pred_ratio = nb_preds.get(cell["id"], 1.0)
            cells_with_ranks.append((pred_ratio * n_code, cell["id"]))

        cells_with_ranks.sort(key=lambda x: x[0])
        ordered_ids = [c[1] for c in cells_with_ranks]
        val_pred_rows.append({"id": nb_id, "cell_order": " ".join(ordered_ids)})

    df_val_pred_final = pd.DataFrame(val_pred_rows)

    # Ground Truth
    df_val_gt = df_val_sample[["id", "cell_order"]]

    # Calculate Metric
    score = calc_kendall_tau(df_val_gt, df_val_pred_final)
    print(f"Validation Kendall Tau Score: {score:.4f}")

    # Basic sanity check: Score should be between -1 and 1 (usually > 0 for a trained model,
    # though with 1 epoch and 20 samples it might be poor)
    assert -1.0 <= score <= 1.0, "Kendall Tau score out of bounds."

    print("\n>>> Demo Completed Successfully!")


if __name__ == "__main__":
    run_demo()
