import os
import sys
import shutil
import numpy as np
import torch
import pandas as pd

# Import from the provided library
from library.config import Config
from library.utils import seed_everything, format_prediction_string
from library.dataset import get_dataloaders, get_test_dataloader
from library.model import EfficientNetUnet
from library.loss import HybridLoss
from library.engine import train_one_epoch, evaluate


def main():
    print("Starting demonstration script...")

    # 1. Setup & Configuration Override
    # We override the Config to run a fast debug session
    demo_dir = "./working/demo_execution"
    if os.path.exists(demo_dir):
        shutil.rmtree(demo_dir)
    os.makedirs(demo_dir, exist_ok=True)

    print(f"Configuring environment. Working directory: {demo_dir}")

    # Patch Config paths to use the demo directory
    Config.WORKING_DIR = demo_dir
    Config.TRAIN_CACHE_IMAGES = os.path.join(demo_dir, "train_images.npy")
    Config.TRAIN_CACHE_MASKS = os.path.join(demo_dir, "train_masks.npy")
    Config.TRAIN_CACHE_LABELS = os.path.join(demo_dir, "train_labels.npy")
    Config.VAL_CACHE_IMAGES = os.path.join(demo_dir, "val_images.npy")
    Config.VAL_CACHE_MASKS = os.path.join(demo_dir, "val_masks.npy")
    Config.VAL_CACHE_LABELS = os.path.join(demo_dir, "val_labels.npy")
    Config.TEST_CACHE_IMAGES = os.path.join(demo_dir, "test_images.npy")
    Config.TEST_CACHE_DIMS = os.path.join(demo_dir, "test_dims.parquet")
    Config.MODEL_SAVE_PATH = os.path.join(demo_dir, "best_model.pth")
    Config.SUBMISSION_PATH = os.path.join(demo_dir, "submission.csv")

    # Patch Hyperparameters for speed
    Config.DEBUG = True
    Config.DEBUG_SAMPLE_SIZE = 32  # Small subset
    Config.BATCH_SIZE = 4
    Config.EPOCHS = 1
    Config.NUM_WORKERS = 2

    # Set seeds for reproducibility
    seed_everything(Config.SEED)

    # 2. Data Loading
    print("\n--- Initializing Data Loaders ---")
    train_loader, val_loader = get_dataloaders(
        load_cached_data=False,  # Force processing of the debug subset
        batch_size=Config.BATCH_SIZE,
    )

    # Verify Train Loader
    images, labels, masks = next(iter(train_loader))
    print(
        f"Train Batch Shapes - Images: {images.shape}, Labels: {labels.shape}, Masks: {masks.shape}"
    )

    # Assertions to verify data integrity
    assert images.shape == (
        Config.BATCH_SIZE,
        3,
        Config.IMG_SIZE,
        Config.IMG_SIZE,
    ), "Incorrect Image Shape"
    assert labels.shape == (
        Config.BATCH_SIZE,
        Config.NUM_STUDY_CLASSES,
    ), "Incorrect Label Shape"
    assert masks.shape == (
        Config.BATCH_SIZE,
        1,
        Config.IMG_SIZE,
        Config.IMG_SIZE,
    ), "Incorrect Mask Shape"
    assert images.dtype == torch.float32, "Images should be float32 tensors"

    # 3. Model Initialization
    print("\n--- Initializing Model ---")
    device = Config.DEVICE
    model = EfficientNetUnet(
        encoder_name=Config.ENCODER_NAME,
        pretrained=True,
        num_study_classes=Config.NUM_STUDY_CLASSES,
    ).to(device)

    # Verify Forward Pass
    dummy_input = torch.randn(2, 3, Config.IMG_SIZE, Config.IMG_SIZE).to(device)
    with torch.no_grad():
        cls_logits, seg_logits = model(dummy_input)

    print(f"Model Output Shapes - Cls: {cls_logits.shape}, Seg: {seg_logits.shape}")
    assert cls_logits.shape == (
        2,
        Config.NUM_STUDY_CLASSES,
    ), "Incorrect Classification Output Shape"
    assert seg_logits.shape == (
        2,
        1,
        Config.IMG_SIZE,
        Config.IMG_SIZE,
    ), "Incorrect Segmentation Output Shape"

    # 4. Training Loop
    print("\n--- Starting Training Loop (1 Epoch) ---")
    criterion = HybridLoss(
        seg_weight=Config.SEG_LOSS_WEIGHT, cls_weight=Config.CLS_LOSS_WEIGHT
    ).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=Config.LEARNING_RATE)

    avg_loss = train_one_epoch(
        train_loader, model, criterion, optimizer, device, epoch=0
    )
    print(f"Training completed. Average Loss: {avg_loss:.4f}")
    assert not np.isnan(avg_loss), "Training loss is NaN"

    # 5. Evaluation
    print("\n--- Starting Evaluation ---")
    val_loss, map_score = evaluate(val_loader, model, criterion, device)
    print(f"Evaluation completed. Val Loss: {val_loss:.4f}, mAP: {map_score:.4f}")

    # 6. Inference & Submission
    print("\n--- Generating Submission ---")
    test_loader = get_test_dataloader(
        load_cached_data=False,
        batch_size=Config.BATCH_SIZE,
    )

    # Load test dims for rescaling (simulated here as we are in debug mode and might not have full parquet)
    # In a real run, we would load the parquet file generated by get_test_dataloader
    if os.path.exists(Config.TEST_CACHE_DIMS):
        test_dims_df = pd.read_parquet(Config.TEST_CACHE_DIMS)
    else:
        # Fallback if debug mode skipped saving (though get_test_dataloader should save it)
        test_dims_df = pd.DataFrame(columns=["id", "width", "height", "study_id"])

    model.eval()
    submission_rows = []

    # Iterate through test set
    # Note: In this debug run, we iterate the loader.
    # Since we don't have the original metadata linked directly in the loader loop (it returns images),
    # we usually rely on the order matching the metadata or a custom collate.
    # For this demo, we will just demonstrate the prediction formatting logic.

    with torch.no_grad():
        for batch_idx, (images, _, _) in enumerate(test_loader):
            images = images.to(device)
            cls_logits, seg_logits = model(images)

            # Predictions
            cls_probs = torch.sigmoid(cls_logits).cpu().numpy()
            seg_probs = torch.sigmoid(seg_logits).cpu().numpy()

            batch_size = images.size(0)
            for i in range(batch_size):
                # Study Level Prediction
                # Get class with max probability for demonstration
                study_pred_idx = np.argmax(cls_probs[i])
                study_label = Config.ID2LABEL[study_pred_idx]
                study_conf = cls_probs[i, study_pred_idx]

                # Image Level Prediction (Boxes)
                # Simple thresholding
                mask = seg_probs[i, 0] > 0.5
                # In real scenario: use cv2.findContours to get boxes
                # Here we use a dummy box for demonstration if mask is empty
                if mask.sum() > 0:
                    # Dummy box logic for demo: bounding rect of whole mask
                    rows = np.any(mask, axis=1)
                    cols = np.any(mask, axis=0)
                    y_min, y_max = np.where(rows)[0][[0, -1]]
                    x_min, x_max = np.where(cols)[0][[0, -1]]
                    box = [x_min, y_min, x_max, y_max]
                    image_label = "opacity"
                else:
                    box = None
                    image_label = "none"

                # Format String
                # Note: This ID logic is simplified for the demo.
                # Real submission requires mapping back to specific IDs from metadata.
                row_id = f"demo_id_{batch_idx}_{i}"

                if box:
                    pred_str = format_prediction_string([image_label], [0.9], [box])
                else:
                    pred_str = "none 1 0 0 1 1"

                submission_rows.append(
                    {"id": f"{row_id}_image", "PredictionString": pred_str}
                )

                # Add study row
                study_str = f"{study_label} {study_conf:.4f} 0 0 1 1"
                submission_rows.append(
                    {"id": f"{row_id}_study", "PredictionString": study_str}
                )

    # Save Submission
    sub_df = pd.DataFrame(submission_rows)
    sub_df.to_csv(Config.SUBMISSION_PATH, index=False)
    print(f"Submission saved to {Config.SUBMISSION_PATH} with {len(sub_df)} rows.")

    print("\nDemonstration complete. Success.")


if __name__ == "__main__":
    main()
