import os
import sys
import pandas as pd
import numpy as np
import shutil

# Ensure the library is in the path if needed, though usually '.' is in pythonpath.
sys.path.append(".")

from library.config import Config
from library.utils import get_atomic_properties
from library.data_loader import build_dataset
from library.model import (
    run_physics_informed_pipeline,
    train_target_model,
    predict_target,
)


def main():
    print("Starting demonstration of Physics-Informed Feature Engineering Pipeline...")

    # 1. Configure for Speed (Demo Mode)
    # We override the configuration to use a very small number of estimators
    # and a temporary working directory for this demo run.
    print("\n[Demo] Configuring parameters for fast execution...")
    Config.XGB_PARAMS["n_estimators"] = 10
    Config.XGB_PARAMS["max_depth"] = 3
    Config.WORKING_DIR = "./working/demo_execution"
    Config.TRAIN_FEATURES_PATH = os.path.join(
        Config.WORKING_DIR, "train_features.parquet"
    )
    Config.VAL_FEATURES_PATH = os.path.join(Config.WORKING_DIR, "val_features.parquet")
    Config.TEST_FEATURES_PATH = os.path.join(
        Config.WORKING_DIR, "test_features.parquet"
    )

    # Ensure the demo working directory exists
    if os.path.exists(Config.WORKING_DIR):
        shutil.rmtree(Config.WORKING_DIR)
    Config.setup()

    # 2. Test Utility Functions
    print("\n[Demo] Testing Utility Functions...")
    props = get_atomic_properties("Ga")
    print(f"Properties for Ga: {props}")
    assert props["Z"] == 31, "Atomic number for Ga should be 31"

    # 3. Load Data and Generate Features (Debug Mode)
    # This step uses data_loader.py which calls features.py
    # We use debug=True to load only a small subset (e.g., 10 samples)
    print("\n[Demo] Building Dataset (Debug Mode)...")
    train_df, val_df, test_df = build_dataset(
        load_cached_data=False,  # Force re-computation to demonstrate feature extraction logic
        debug=True,
        debug_sample_size=10,
    )

    # 4. Verify Data Integrity
    print("\n[Demo] Verifying Data Integrity...")
    print(f"Train shape: {train_df.shape}")
    print(f"Val shape:   {val_df.shape}")
    print(f"Test shape:  {test_df.shape}")

    # Check for expected feature columns generated by features.py
    expected_features = [
        "geo_volume",
        "geo_density",
        "disorder_en_var",
        "disorder_r_var",
        "electro_mean",
        "electro_std",
        "electro_max",
    ]

    for feat in expected_features:
        assert feat in train_df.columns, f"Feature {feat} missing in training data"
        assert feat in test_df.columns, f"Feature {feat} missing in test data"

    # Check for target columns in train/val
    for target in Config.TARGET_COLS:
        assert target in train_df.columns, f"Target {target} missing in training data"
        assert target in val_df.columns, f"Target {target} missing in validation data"
        # Test data should NOT have targets
        if target in test_df.columns:
            print(
                f"Note: {target} present in test_df (likely from metadata file if available, or artifact)."
            )

    print("Data integrity checks passed.")

    # 5. Run Model Pipeline
    # This uses model.py to train XGBoost models and generate predictions
    print("\n[Demo] Running Model Training and Prediction Pipeline...")
    trained_models = run_physics_informed_pipeline(train_df, val_df, test_df)

    # 6. Verify Output
    print("\n[Demo] Verifying Submission File...")
    if os.path.exists(Config.SUBMISSION_PATH):
        submission = pd.read_csv(Config.SUBMISSION_PATH)
        print(f"Submission file created at {Config.SUBMISSION_PATH}")
        print(f"Submission shape: {submission.shape}")

        # Check columns
        assert "id" in submission.columns
        for target in Config.TARGET_COLS:
            assert target in submission.columns

        # Check if we have predictions for the debug subset
        # Note: In debug mode, test_df is small, so submission will be small
        assert len(submission) == len(
            test_df
        ), "Submission row count does not match test set size"

        print("Submission verification successful.")
    else:
        raise FileNotFoundError("Submission file was not created.")

    print("\n[Demo] Demonstration Completed Successfully.")


if __name__ == "__main__":
    main()
